using System.Text;

namespace BlazorCompose.Site.DocGen;

/// <summary>Emits the committed Docs.g.cs source: one public const string per document,
/// sorted by identifier (Ordinal), HTML escaped into a regular double-quoted literal,
/// LF newlines only, with an auto-generated header so repo-wide analyzers/style rules
/// do not treat the generated file as hand-written code.</summary>
public static class CSharpDocEmitter
{
    public static string Emit(IReadOnlyList<(string Identifier, string Html)> docs)
    {
        ArgumentNullException.ThrowIfNull(docs);

        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var (identifier, _) in docs)
        {
            if (!seen.Add(identifier))
            {
                throw new InvalidOperationException(
                    $"Duplicate document identifier '{identifier}'. Two content files map to the same C# member name.");
            }
        }

        var ordered = docs.OrderBy(d => d.Identifier, StringComparer.Ordinal).ToList();

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");
        sb.Append("namespace BlazorCompose.Site.Content;\n\n");
        sb.Append("public static class Docs\n{\n");

        for (int i = 0; i < ordered.Count; i++)
        {
            var (identifier, html) = ordered[i];
            sb.Append("    public const string ").Append(identifier).Append(" =\n");
            sb.Append("        \"").Append(Escape(html)).Append("\";\n");
            if (i < ordered.Count - 1)
            {
                sb.Append('\n');
            }
        }

        sb.Append("}\n");
        return sb.ToString();
    }

    private static string Escape(string s)
    {
        var sb = new StringBuilder(s.Length + 16);
        foreach (char c in s)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (c < ' ')
                    {
                        sb.Append("\\u").Append(((int)c).ToString("x4", System.Globalization.CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        sb.Append(c);
                    }
                    break;
            }
        }

        return sb.ToString();
    }
}
