using System.Globalization;
using System.Text;

namespace BlazorCodeFirst.Site.DocGen;

/// <summary>Emits the committed Docs.g.cs source: a DocEntry record plus the Docs manifest
/// (All + Find), ordered by (Order, Slug), HTML and titles escaped into regular double-quoted
/// literals, LF newlines only, with an auto-generated header so repo-wide analyzers/style rules
/// do not treat the generated file as hand-written code.</summary>
public static class CSharpDocEmitter
{
    public static string Emit(IReadOnlyList<(DocMeta Meta, string Html)> docs)
    {
        ArgumentNullException.ThrowIfNull(docs);

        var seenSlugs = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var seenOrders = new HashSet<int>();
        foreach (var (meta, _) in docs)
        {
            if (!seenSlugs.Add(meta.Slug))
            {
                throw new InvalidOperationException(
                    $"Duplicate document slug '{meta.Slug}'. Two content files map to the same /docs route.");
            }

            if (!seenOrders.Add(meta.Order))
            {
                throw new InvalidOperationException(
                    $"Duplicate front matter order {meta.Order} (slug '{meta.Slug}'). " +
                    "Each document must declare a distinct 'order' so navigation ordering is unambiguous.");
            }
        }

        // Order is unique (enforced above); the slug tie-break only keeps the output deterministic
        // should that ever change.
        var ordered = docs
            .OrderBy(d => d.Meta.Order)
            .ThenBy(d => d.Meta.Slug, StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");
        // Required before nullable annotations may appear in an auto-generated file (CS8669).
        sb.Append("#nullable enable\n");
        sb.Append("using System.Collections.Immutable;\n\n");
        sb.Append("namespace BlazorCodeFirst.Site.Content;\n\n");
        sb.Append("/// <summary>One document's navigation metadata and its build-time converted HTML.</summary>\n");
        sb.Append("public sealed record DocEntry(string Slug, string Title, int Order, string Html);\n\n");
        sb.Append("/// <summary>The generated documentation manifest, ordered by (Order, Slug).</summary>\n");
        sb.Append("public static class Docs\n{\n");
        sb.Append("    public static readonly ImmutableArray<DocEntry> All =\n    [\n");

        foreach (var (meta, html) in ordered)
        {
            sb.Append("        new DocEntry(\n");
            sb.Append("            \"").Append(Escape(meta.Slug)).Append("\",\n");
            sb.Append("            \"").Append(Escape(meta.Title)).Append("\",\n");
            sb.Append("            ").Append(meta.Order.ToString(CultureInfo.InvariantCulture)).Append(",\n");
            sb.Append("            \"").Append(Escape(html)).Append("\"),\n");
        }

        sb.Append("    ];\n\n");
        sb.Append("    /// <summary>Finds a document by slug. Blazor route matching is case-insensitive,\n");
        sb.Append("    /// so the lookup must be too.</summary>\n");
        sb.Append("    public static DocEntry? Find(string? slug)\n    {\n");
        sb.Append("        if (slug is null)\n        {\n            return null;\n        }\n\n");
        sb.Append("        foreach (var entry in All)\n        {\n");
        sb.Append("            if (string.Equals(entry.Slug, slug, StringComparison.OrdinalIgnoreCase))\n");
        sb.Append("            {\n                return entry;\n            }\n");
        sb.Append("        }\n\n        return null;\n    }\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    private static string Escape(string s)
    {
        var sb = new StringBuilder(s.Length + 16);
        foreach (char c in s)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    // U+0085 (NEL), U+2028 (LINE SEPARATOR), and U+2029 (PARAGRAPH SEPARATOR)
                    // are >= 0x20 but are classified as new-line-characters by the C# lexer,
                    // so they are forbidden inside a non-verbatim string literal (CS1010) and
                    // must be escaped just like the control characters below 0x20.
                    if (c is < ' ' or '\u0085' or '\u2028' or '\u2029')
                    {
                        sb.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        sb.Append(c);
                    }
                    break;
            }
        }

        return sb.ToString();
    }
}
