using System.Text;

namespace BlazorCodeFirst.Site.DocGen;

/// <summary>Emits the committed Snippets.g.cs source: one <c>const string</c> of highlighted HTML
/// per declared snippet, ordered by member name, LF newlines only, with an auto-generated header so
/// repository-wide analyzers do not treat it as hand-written code.</summary>
/// <remarks>
/// The members are constants rather than a lookup, because every caller names the snippet it wants
/// at compile time. A constant also folds: <c>Raw(Snippets.Hero)</c> reaches the generator as a
/// literal, so a figure costs one <c>AddMarkupContent</c> frame, which is what the hand-spelled
/// spans it replaces already cost.
/// </remarks>
public static class CSharpSnippetEmitter
{
    public static string Emit(IReadOnlyList<(SnippetEntry Entry, string Html)> snippets)
    {
        ArgumentNullException.ThrowIfNull(snippets);

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");
        sb.Append("#nullable enable\n\n");
        sb.Append("namespace BlazorCodeFirst.Site.Content;\n\n");
        sb.Append("/// <summary>The build-time highlighted HTML of each declared code figure.</summary>\n");
        sb.Append("/// <remarks>Generated by DocGen from site/snippets/manifest. Each value is the\n");
        sb.Append("/// Html.Raw trust boundary: repository-owned source, converted at authoring time.</remarks>\n");
        sb.Append("public static class Snippets\n");
        sb.Append("{\n");

        bool first = true;
        foreach (var (entry, html) in snippets.OrderBy(s => s.Entry.MemberName, StringComparer.Ordinal))
        {
            if (!first)
            {
                sb.Append('\n');
            }

            first = false;
            sb.Append("    /// <summary>The figure read from <c>").Append(entry.Path).Append("</c>.</summary>\n");
            sb.Append("    public const string ").Append(entry.MemberName).Append(" = \"")
              .Append(CSharpLiteral.Escape(html)).Append("\";\n");
        }

        sb.Append("}\n");
        return sb.ToString();
    }
}
