using System.Text;

namespace BlazorCodeFirst.Site.DocGen;

/// <summary>Emits the committed Snippets.g.cs source: one <c>const string</c> of highlighted HTML
/// per declared snippet, ordered by member name, LF newlines only, with an auto-generated header so
/// repository-wide analyzers do not treat it as hand-written code.</summary>
/// <remarks>
/// The members are constants rather than a lookup, because every caller names the snippet it wants
/// at compile time. A constant also folds: <c>Raw(Snippets.Hero)</c> reaches the generator as a
/// literal, so a figure costs one <c>AddMarkupContent</c> frame, which is what the hand-spelled
/// spans it replaces already cost.
/// </remarks>
public static class CSharpSnippetEmitter
{
    public static string Emit(IReadOnlyList<(SnippetEntry Entry, string Html)> snippets)
    {
        ArgumentNullException.ThrowIfNull(snippets);

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");
        sb.Append("#nullable enable\n\n");
        sb.Append("namespace BlazorCodeFirst.Site.Content;\n\n");
        sb.Append("/// <summary>The build-time highlighted HTML of each declared code figure.</summary>\n");
        sb.Append("/// <remarks>Generated by DocGen from site/snippets/manifest. Each value is the\n");
        sb.Append("/// Html.Raw trust boundary: repository-owned source, converted at authoring time.</remarks>\n");
        sb.Append("public static class Snippets\n");
        sb.Append("{\n");

        // The path is quoted as the manifest declares it, which is where a reader goes to change it.
        // Escaped, because it lands in XML: a path holding an ampersand would otherwise emit a doc
        // comment that does not parse, and the escaping rule this file already keeps for the value
        // would have an exception one line above it.
        sb.Append(string.Join('\n', snippets
            .OrderBy(s => s.Entry.MemberName, StringComparer.Ordinal)
            .Select(s =>
                $"    /// <summary>The figure DocGen read for <c>{XmlText.Escape(s.Entry.Name)}</c>, "
                    + $"declared in the snippets manifest as <c>{XmlText.Escape(s.Entry.Path)}</c>.</summary>\n"
                + $"    public const string {s.Entry.MemberName} = \"{CSharpLiteral.Escape(s.Html)}\";\n")));

        sb.Append("}\n");
        return sb.ToString();
    }
}
