// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219, CS8601, CS8620

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        string __bcf_arg_0_0 = "Heading";
        global::System.Collections.Generic.List<string> __bcf_arg_0_1 = _items;
        __builder.OpenElement(0, "div");
        __builder.AddAttribute(1, "class", "panel");
        __builder.AddMarkupContent(2, "<h2>Heading</h2>");
        __builder.OpenElement(3, "ul");
        __builder.OpenRegion(4);
        foreach (var __bcf_item_5 in __bcf_arg_0_1)
        {
            __builder.OpenElement(5, "li");
            __builder.SetKey(__bcf_item_5);
            __builder.AddContent(6, $"{__bcf_arg_0_0}:{__bcf_item_5}");
            __builder.CloseElement();
        }
        __builder.CloseRegion();
        __builder.CloseElement();
        __builder.CloseElement();
    }
}
