// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenComponent<global::T.Card>(0);
        __builder.AddComponentParameter(1, "Title", (global::System.String?)("t"));
        __builder.AddComponentParameter(2, "HeaderTemplate", (global::Microsoft.AspNetCore.Components.RenderFragment<global::System.Int32>)((_) => (__builder) =>
        {
            __builder.AddMarkupContent(3, "<span>heading</span>");
        }));
        __builder.AddComponentParameter(4, "RowTemplate", (global::Microsoft.AspNetCore.Components.RenderFragment<global::System.Int32>)((__bcf_context_3) => (__builder) =>
        {
            __builder.OpenElement(5, "span");
            __builder.AddContent(6, $"Row {__bcf_context_3}");
            __builder.CloseElement();
        }));
        __builder.CloseComponent();
    }
}
