// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219, CS8601, CS8620

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenComponent<global::T.Card>(0);
        __builder.AddComponentParameter(1, "Title", "t");
        __builder.AddComponentParameter(2, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder) =>
        {
            __builder.AddMarkupContent(3, "<div>x</div>");
        }));
        __builder.CloseComponent();
    }
}
