// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenElement(0, "input");
        __builder.AddAttribute(1, "value", _live);
        #pragma warning disable CS8601, CS8620
        __builder.AddAttribute(2, "oninput", global::Microsoft.AspNetCore.Components.EventCallbackFactoryBinderExtensions.CreateBinder(global::Microsoft.AspNetCore.Components.EventCallback.Factory, this, __value => _live = __value, _live));
        #pragma warning restore CS8601, CS8620
        __builder.SetUpdatesAttributeName("value");
        __builder.AddAttribute(3, "data-committed", _committed);
        #pragma warning disable CS8601, CS8620
        __builder.AddAttribute(4, "onchange", global::Microsoft.AspNetCore.Components.EventCallbackFactoryBinderExtensions.CreateBinder(global::Microsoft.AspNetCore.Components.EventCallback.Factory, this, __value => _committed = __value, _committed));
        #pragma warning restore CS8601, CS8620
        __builder.CloseElement();
    }
}
