// ===== T.NullAndBare.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219

namespace T;

partial class NullAndBare
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenElement(0, "form");
        __builder.AddMarkupContent(1, "<input type=\"checkbox\" checked=\"\">");
        __builder.OpenElement(2, "button");
        __builder.AddAttribute(3, "disabled", _saving);
        __builder.AddAttribute(4, "title", _tip);
        __builder.AddContent(5, "Save");
        __builder.CloseElement();
        __builder.CloseElement();
    }
}
