// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219, CS8601, CS8620

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenElement(0, "div");
        __builder.AddAttribute(1, "class", "shell");
        __builder.OpenElement(2, "span");
        __builder.AddContent(3, $"Count: {_count}");
        __builder.CloseElement();
        __builder.AddContent(4, "bare text");
        __builder.OpenElement(5, "button");
        __builder.AddAttribute(6, "onclick", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, () => _count++));
        __builder.AddContent(7, "Go");
        __builder.CloseElement();
        __builder.CloseElement();
    }
}
