// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenElement(0, "a");
        __builder.AddAttribute(1, "href", "/");
        __builder.AddAttribute(2, "title", "home");
        __builder.AddContent(3, "Home");
        __builder.CloseElement();
    }
}
