// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219, CS1591

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenElement(0, "div");
        __builder.AddAttribute(1, "onmouseenter", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, () => _count++));
        __builder.AddMarkupContent(2, "<span>a</span>");
        __builder.CloseElement();
    }
}
