// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenElement(0, "button");
        __builder.AddAttribute(1, "onclick", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, () => _count++));
        __builder.AddContent(2, "Increment");
        __builder.CloseElement();
    }
}
