// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219, CS8601, CS8620

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenElement(0, "ul");
        __builder.AddAttribute(1, "class", "nav-list");
        __builder.OpenRegion(2);
        foreach (var __bcf_item_1 in _items)
        {
            __builder.OpenElement(3, "li");
            __builder.SetKey(__bcf_item_1);
            __builder.AddContent(4, __bcf_item_1);
            __builder.CloseElement();
        }
        __builder.CloseRegion();
        __builder.CloseElement();
    }
}
