// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219, CS8601, CS8620

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenElement(0, "ul");
        __builder.OpenRegion(1);
        foreach (var __bcf_item_1 in _items)
        {
            __builder.OpenElement(2, "li");
            __builder.SetKey(__bcf_item_1);
            __builder.OpenElement(3, "a");
            __builder.AddAttribute(4, "href", $"/{__bcf_item_1}");
            __builder.AddContent(5, __bcf_item_1);
            __builder.CloseElement();
            __builder.CloseElement();
        }
        __builder.CloseRegion();
        __builder.CloseElement();
    }
}
