// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenElement(0, "div");
        __builder.OpenElement(1, "p");
        __builder.AddContent(2, "a");
        __builder.CloseElement();
        __builder.OpenElement(3, "p");
        __builder.AddContent(4, "b");
        __builder.CloseElement();
        __builder.AddMarkupContent(5, "<em>trusted</em>");
        __builder.CloseElement();
    }
}
