// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219, CS8601, CS8620

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenElement(0, "div");
        __builder.AddMarkupContent(1, "<p>a</p><p>b</p>");
        __builder.AddMarkupContent(2, "<em>trusted</em>");
        __builder.CloseElement();
    }
}
