// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219, CS1591

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenElement(0, "div");
        __builder.OpenRegion(1);
        if (_on)
        {
            __builder.AddMarkupContent(2, "<span>Yes</span>");
        }
        __builder.CloseRegion();
        __builder.CloseElement();
    }
}
