// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219, CS8601, CS8620

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenElement(0, "div");
        __builder.AddAttribute(1, "class", "shell");
        __builder.OpenRegion(2);
        if (_on)
        {
            __builder.AddMarkupContent(3, "<span>Yes</span>");
        }
        else
        {
            __builder.AddMarkupContent(4, "<span>No</span>");
        }
        __builder.CloseRegion();
        __builder.CloseElement();
    }
}
