// ===== T.Shell.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219

namespace T;

partial class Shell
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenElement(0, "main");
        __builder.AddAttribute(1, "class", "shell");
        __builder.AddContent(2, Body);
        __builder.CloseElement();
    }
}
