// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219, CS1591

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenElement(0, "ul");
        __builder.AddMarkupContent(1, "<li>first</li>");
        __builder.OpenRegion(2);
        foreach (var __bcf_item_3 in _items)
        {
            __builder.OpenElement(3, "li");
            __builder.AddAttribute(4, "class", "row");
            __builder.AddContent(5, __bcf_item_3);
            __builder.CloseElement();
        }
        __builder.CloseRegion();
        __builder.AddMarkupContent(6, "<li>last</li>");
        __builder.CloseElement();
    }
}
