// ===== T.First.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219, CS1591

namespace T;

partial class First
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.AddMarkupContent(0, "<div class=\"a\"><span>first</span></div>");
    }
}

// ===== T.Second.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219, CS1591

namespace T;

partial class Second
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.AddMarkupContent(0, "<p>second</p>");
    }
}
