// ===== T.First.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219

namespace T;

partial class First
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenElement(0, "div");
        __builder.AddAttribute(1, "class", "a");
        __builder.OpenElement(2, "span");
        __builder.AddContent(3, "first");
        __builder.CloseElement();
        __builder.CloseElement();
    }
}

// ===== T.Second.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219

namespace T;

partial class Second
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenElement(0, "p");
        __builder.AddContent(1, "second");
        __builder.CloseElement();
    }
}
