// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenComponent<global::T.Card>(0);
        __builder.AddComponentParameter(1, "Footer", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder) =>
        {
            __builder.OpenElement(2, "div");
            __builder.AddContent(3, "f");
            __builder.CloseElement();
        }));
        __builder.CloseComponent();
    }
}
