// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        string __bc_arg_0_0 = "Heading";
        global::System.Collections.Generic.List<string> __bc_arg_0_1 = _items;
        __builder.OpenElement(0, "div");
        __builder.AddAttribute(1, "class", "panel");
        __builder.OpenElement(2, "h2");
        __builder.AddContent(3, __bc_arg_0_0);
        __builder.CloseElement();
        __builder.OpenElement(4, "ul");
        __builder.OpenRegion(5);
        foreach (var __bc_item_5 in __bc_arg_0_1)
        {
            __builder.OpenElement(6, "li");
            __builder.SetKey(__bc_item_5);
            __builder.AddContent(7, $"{__bc_arg_0_0}:{__bc_item_5}");
            __builder.CloseElement();
        }
        __builder.CloseRegion();
        __builder.CloseElement();
        __builder.CloseElement();
    }
}
