// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenElement(0, "div");
        __builder.AddAttribute(1, "class", "shell");
        __builder.OpenComponent<global::T.Card>(2);
        __builder.AddComponentParameter(3, "Title", "t");
        __builder.CloseComponent();
        __builder.CloseElement();
    }
}
