// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenComponent<global::T.Card>(0);
        __builder.AddComponentParameter(1, "Title", "t");
        __builder.AddComponentParameter(2, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder) =>
        {
            __builder.OpenElement(3, "div");
            __builder.AddContent(4, "x");
            __builder.CloseElement();
        }));
        __builder.CloseComponent();
    }
}
