// ===== T.Host.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219

namespace T;

partial class Host
{
    protected override void RenderView(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
    {
        __builder.OpenElement(0, "div");
        __builder.AddAttribute(1, "class", "shell");
        __builder.OpenRegion(2);
        if (_on)
        {
            __builder.OpenElement(3, "span");
            __builder.AddContent(4, "Yes");
            __builder.CloseElement();
        }
        else
        {
            __builder.OpenElement(5, "span");
            __builder.AddContent(6, "No");
            __builder.CloseElement();
        }
        __builder.CloseRegion();
        __builder.CloseElement();
    }
}
