using BlazorCompose.Site.DocGen;
using Xunit;

namespace BlazorCompose.Site.DocGen.Tests;

public class CSharpDocEmitterTests
{
    private static string EmitOne(string slug, string title, int order, string html) =>
        CSharpDocEmitter.Emit([(new DocMeta(slug, title, order), html)]);

    [Fact]
    public void Emit_ProducesManifestShape()
    {
        string source = EmitOne("getting-started", "Getting Started", 10, "<p>hi</p>");

        Assert.StartsWith("// <auto-generated/>\n", source);
        Assert.Contains("namespace BlazorCompose.Site.Content;", source);
        Assert.Contains("public sealed record DocEntry(string Slug, string Title, int Order, string Html);", source);
        Assert.Contains("public static readonly ImmutableArray<DocEntry> All", source);
        Assert.Contains("public static DocEntry? Find(string? slug)", source);
        Assert.Contains("\"getting-started\"", source);
        Assert.Contains("\"Getting Started\"", source);
        Assert.Contains("<p>hi</p>", source);
    }

    [Fact]
    public void Emit_EnablesNullableContext()
    {
        // An auto-generated file needs an explicit #nullable directive before it may use nullable
        // annotations (CS8669), and Find's signature is annotated.
        string source = EmitOne("a", "A", 1, "<p/>");

        Assert.Contains("#nullable enable", source);
        Assert.True(
            source.IndexOf("#nullable enable", StringComparison.Ordinal)
                < source.IndexOf("DocEntry? Find", StringComparison.Ordinal),
            "the directive must precede the annotated signature");
    }

    [Fact]
    public void Emit_OrdersByFrontMatterOrder()
    {
        string source = CSharpDocEmitter.Emit(
        [
            (new DocMeta("zeta", "Zeta", 30), "<p>z</p>"),
            (new DocMeta("beta", "Beta", 20), "<p>b</p>"),
            (new DocMeta("alpha", "Alpha", 10), "<p>a</p>"),
        ]);

        int alpha = source.IndexOf("\"alpha\"", StringComparison.Ordinal);
        int beta = source.IndexOf("\"beta\"", StringComparison.Ordinal);
        int zeta = source.IndexOf("\"zeta\"", StringComparison.Ordinal);

        Assert.True(alpha < beta && beta < zeta, "documents must be emitted in ascending order");
    }

    [Fact]
    public void Emit_UsesOrdinalIgnoreCaseLookup() =>
        Assert.Contains("OrdinalIgnoreCase", EmitOne("a", "A", 1, "<p/>"));

    [Fact]
    public void Emit_EscapesHtmlIntoStringLiteral()
    {
        string source = EmitOne("a", "A", 1, "<a href=\"/x\">\n</a>");

        Assert.Contains("\\\"", source);   // quotes escaped
        Assert.Contains("\\n", source);    // newlines escaped
        Assert.DoesNotContain("\r", source);
    }

    [Fact]
    public void Emit_EscapesQuotesInTitle() =>
        Assert.Contains("\\\"Quoted\\\"", EmitOne("a", "\"Quoted\"", 1, "<p/>"));

    [Fact]
    public void Emit_DuplicateSlug_Throws()
    {
        var ex = Assert.Throws<InvalidOperationException>(() => CSharpDocEmitter.Emit(
        [
            (new DocMeta("dup", "One", 1), "<p>1</p>"),
            (new DocMeta("dup", "Two", 2), "<p>2</p>"),
        ]));

        Assert.Contains("dup", ex.Message);
    }

    [Fact]
    public void Emit_DuplicateOrder_Throws()
    {
        var ex = Assert.Throws<InvalidOperationException>(() => CSharpDocEmitter.Emit(
        [
            (new DocMeta("a", "A", 10), "<p>a</p>"),
            (new DocMeta("b", "B", 10), "<p>b</p>"),
        ]));

        Assert.Contains("order", ex.Message, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("10", ex.Message);
    }

    [Fact]
    public void Emit_IsDeterministic() =>
        Assert.Equal(EmitOne("a", "A", 1, "<p>x</p>"), EmitOne("a", "A", 1, "<p>x</p>"));
}
