using BlazorCompose.Site.DocGen;
using Xunit;

namespace BlazorCompose.Site.DocGen.Tests;

public class CSharpDocEmitterTests
{
    [Fact]
    public void Emit_ProducesAutoGeneratedClassWithConst()
    {
        string src = CSharpDocEmitter.Emit([("Intro", "<h1>Hi</h1>")]);

        Assert.StartsWith("// <auto-generated/>", src);
        Assert.Contains("namespace BlazorCompose.Site.Content;", src);
        Assert.Contains("public static class Docs", src);
        Assert.Contains("public const string Intro =", src);
        Assert.Contains("\"<h1>Hi</h1>\"", src);
        Assert.EndsWith("\n", src);
    }

    [Fact]
    public void Emit_EscapesQuotesBackslashesAndNewlines()
    {
        // Input contains: double-quote, backslash, LF, CRLF.
        string html = "a\"b\\c\nd\r\ne";
        string src = CSharpDocEmitter.Emit([("Doc", html)]);

        Assert.Contains("\"a\\\"b\\\\c\\nd\\r\\ne\"", src);
    }

    [Fact]
    public void Emit_SortsMembersByOrdinalIdentifier()
    {
        string src = CSharpDocEmitter.Emit(
        [
            ("Zebra", "z"),
            ("Apple", "a"),
        ]);

        Assert.True(src.IndexOf("Apple", StringComparison.Ordinal)
            < src.IndexOf("Zebra", StringComparison.Ordinal));
    }

    [Fact]
    public void Emit_DuplicateIdentifier_Throws()
    {
        Assert.Throws<InvalidOperationException>(() => CSharpDocEmitter.Emit(
        [
            ("Dup", "1"),
            ("Dup", "2"),
        ]));
    }

    [Fact]
    public void Emit_UsesLfNewlinesOnly()
    {
        string src = CSharpDocEmitter.Emit([("Intro", "<p>x</p>")]);
        Assert.DoesNotContain("\r\n", src);
    }
}
