using System;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;
using System.Text;
using BlazorCodeFirst.Compiler.Generation;
using Microsoft.CodeAnalysis.Text;

namespace BlazorCodeFirst.Compiler;

/// <summary>Emits a <c>RenderView</c> override into the generated partial class.</summary>
internal static class RenderViewEmitter
{
    private const string RtbType =
        "global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder";

    private const string EventCallbackFactory =
        "global::Microsoft.AspNetCore.Components.EventCallback.Factory";

    private const string RenderFragmentType =
        "global::Microsoft.AspNetCore.Components.RenderFragment";

    public static SourceText Emit(ComponentModel model)
    {
        var writer = new IndentedWriter();
        writer.AppendLine("// <auto-generated/>");
        writer.AppendLine("#nullable enable");
        writer.AppendLine("#pragma warning disable CS0219");
        writer.AppendLine();

        if (model.Namespace is { } ns)
        {
            writer.AppendLine($"namespace {ns};");
            writer.AppendLine();
        }

        // A generic component's generated part must repeat the type-parameter list, or it declares a
        // different type and the override does not join the user's class (CS0115 + CS0534). Constraints
        // are omitted deliberately: they belong to the type parameter, so one declaration carrying them
        // is enough (verified), and reproducing them wrongly would reject correct user code.
        var typeParameters = model.TypeParameters.AsImmutableArray();
        var typeParameterList = typeParameters.Length == 0
            ? string.Empty
            : "<" + string.Join(", ", typeParameters) + ">";

        writer.AppendLine($"partial class {model.ClassName}{typeParameterList}");
        writer.AppendLine("{");
        writer.Indent++;
        writer.AppendLine($"protected override void RenderView({RtbType} __builder)");
        writer.AppendLine("{");
        writer.Indent++;

        EmitNode(writer, model.RootNode, startSeq: 0);

        writer.Indent--;
        writer.AppendLine("}");
        writer.Indent--;
        writer.Append("}");

        return SourceText.From(writer.ToString(), Encoding.UTF8);
    }

    // ---------------------------------------------------------------------------
    // Node emission, returns the next available sequence number
    // ---------------------------------------------------------------------------

    /// <param name="key">
    /// When non-<see langword="null"/>, a key expression to apply to this node's root element/component
    /// frame via <c>SetKey</c> immediately after it opens. Supplied only by <see cref="EmitForEach"/> for
    /// the loop content root; the key is consumed by the first element/component and never propagated to
    /// children. Region-rooted nodes (<see cref="IfNode"/>, <see cref="ForEachNode"/>) never receive a
    /// non-<see langword="null"/> key because BCF3003 blocks region-rooted content from reaching emission.
    /// </param>
    private static int EmitNode(IndentedWriter writer, RenderNode node, int startSeq, string? key = null)
    {
        // A folded run is one AddMarkupContent frame, which SetKey cannot attach to. EmitForEach is the
        // only caller that passes a non-null key (for the loop content root), so this check is what keeps
        // a ForEach content root out of the fold; there is no separate predicate to keep in step
        // (ARCHITECTURE.md §2.7(D)).
        if (key is null
            && StaticMarkupSerializer.IsFoldable(node)
            && TryEmitFolded(writer, [node], startSeq, out var afterFold))
        {
            return afterFold;
        }

        // Only three node kinds can receive a threaded key: the two that open a keyable frame and consume
        // it, and the expansion that forwards it to its body's root. Everything else is region-rooted or
        // frameless, and BCF3003 blocks region-rooted content from reaching emission at all, so a key
        // arriving at one of them means a keyable node was wired to this dispatch without updating that
        // contract. Asserted once here, where the split is already visible, rather than restated at each
        // arm that would otherwise take a key it cannot honour.
        Debug.Assert(
            key is null || node is ElementNode or ComponentNode or ExpansionNode,
            $"A key reached '{node.GetType().Name}', which opens no keyable frame; SetKey would be silently dropped.");

        return node switch
        {
            IfNode ifNode => EmitIf(writer, ifNode, startSeq),
            ExpansionNode expansion => EmitExpansion(writer, expansion, startSeq, key),
            ForEachNode forEach => EmitForEach(writer, forEach, startSeq),
            ComponentNode component => EmitComponent(writer, component, startSeq, key),
            ElementNode element => EmitElement(writer, element, startSeq, key),
            TextContentNode text => EmitTextContent(writer, text, startSeq),
            FragmentNode fragment => EmitFragment(writer, fragment, startSeq),
            RawMarkupNode raw => EmitRawMarkup(writer, raw, startSeq),
            RenderFragmentContentNode fragmentContent =>
                EmitRenderFragmentContent(writer, fragmentContent, startSeq),
            _ => throw new NotSupportedException(
                $"Emission for '{node.GetType().Name}' is not yet implemented."),
        };
    }

    /// <summary>
    /// Emits a child list, coalescing maximal runs of consecutive foldable siblings into one
    /// <c>AddMarkupContent</c> frame each, and returns the next available sequence number. The run, not
    /// the subtree, is the fold unit: adjacent static siblings with nothing dynamic between them become
    /// one frame, which is what #142's measurement found the reduction actually comes from.
    /// </summary>
    private static int EmitChildren(IndentedWriter writer, EquatableArray<RenderNode> children, int seq)
    {
        var nodes = children.AsImmutableArray();
        var index = 0;
        while (index < nodes.Length)
        {
            if (!StaticMarkupSerializer.IsFoldable(nodes[index]))
            {
                seq = EmitNode(writer, nodes[index], seq);
                index++;
                continue;
            }

            var runEnd = index + 1;
            while (runEnd < nodes.Length && StaticMarkupSerializer.IsFoldable(nodes[runEnd]))
                runEnd++;

            var run = ImmutableArray.Create(nodes, index, runEnd - index);
            if (TryEmitFolded(writer, run, seq, out var afterFold))
            {
                seq = afterFold;
            }
            else
            {
                // Foldable but not worth folding: emit the run's nodes as they stand.
                for (var inner = index; inner < runEnd; inner++)
                    seq = EmitNode(writer, nodes[inner], seq);
            }

            index = runEnd;
        }

        return seq;
    }

    /// <summary>
    /// Emits <paramref name="run"/> as one <c>AddMarkupContent</c> frame when doing so replaces at least
    /// two frames, and reports the next sequence number through <paramref name="next"/>. A run worth one
    /// frame is left alone: folding it would change the shape without reducing anything.
    /// </summary>
    /// <param name="run">
    /// Nodes that all satisfy <see cref="StaticMarkupSerializer.IsFoldable"/>. Both callers have already
    /// established that — <see cref="EmitChildren"/> because partitioning into runs is how it finds them,
    /// <see cref="EmitNode"/> by testing the single node — so this does not re-derive it. Passing an
    /// unfoldable node throws out of the serializer rather than being quietly declined.
    /// </param>
    /// <remarks>
    /// Whether a fold pays for itself is only known after serializing the run, so the losing case is
    /// unavoidable work. What it need not include is the markup string: the count comes back from
    /// <see cref="StaticMarkupSerializer.WriteTo"/> while the text is still in the builder, and a run that
    /// cannot win is abandoned there. This matters because the losing case is not rare — a lone static text
    /// child absorbs exactly one frame, so every one of them is attempted, declined, and then emitted as a
    /// frame by its caller.
    /// </remarks>
    private static bool TryEmitFolded(
        IndentedWriter writer, ImmutableArray<RenderNode> run, int seq, out int next)
    {
        next = seq;

        var markup = new StringBuilder();
        if (StaticMarkupSerializer.WriteTo(markup, run) < 2)
            return false;

        var literal = global::Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(
            markup.ToString(), quote: true);
        writer.AppendLine($"__builder.AddMarkupContent({seq}, {literal});");
        next = seq + 1;
        return true;
    }

    /// <summary>
    /// Emits the folded <c>class</c> attribute for a decorated element and returns the next sequence
    /// number. All <c>.Class</c> decorations collapse into one attribute frame (ARCHITECTURE.md §2.7(A)):
    /// a single class is emitted verbatim; N≥2 classes are concatenated as <c>(e0) + " " + (e1) + …</c>
    /// with each expression parenthesized so operator precedence (e.g. a ternary or <c>??</c>) is
    /// preserved. When every class is a string literal the C# compiler constant-folds this to one string.
    /// When there is no decoration, no frame is emitted and the sequence is unchanged.
    /// </summary>
    private static int EmitClassAttribute(IndentedWriter writer, EquatableArray<ExpressionTemplate> classes, int seq)
    {
        if (classes.Length == 0)
            return seq;

        var array = classes.AsImmutableArray();
        string value = array.Length == 1
            ? array[0].ToCode()
            : string.Join(" + \" \" + ", array.Select(static c => $"({c.ToCode()})"));

        writer.AppendLine($"__builder.AddAttribute({seq}, \"{ClassChannel.AttributeName}\", {value});");
        return seq + 1;
    }

    private static int EmitIf(IndentedWriter writer, IfNode node, int seq)
    {
        // seq is consumed by OpenRegion.
        // then  branch occupies [seq+1, seq+1+W(then)).
        // else  branch occupies [seq+1+W(then), seq+1+W(then)+W(else)).
        // Both branches are reserved whichever one runs, so a following sibling receives a sequence
        // independent of the condition. The cursor after the last emitted branch *is* that reservation:
        // with no else, `afterThen` already sits at the end of the then range.
        int thenStart = seq + 1;

        writer.AppendLine($"__builder.OpenRegion({seq});");
        writer.AppendLine($"if ({node.ConditionExpression.ToCode()})");
        writer.AppendLine("{");
        writer.Indent++;
        int afterThen = EmitNode(writer, node.Then, thenStart);
        writer.Indent--;
        writer.AppendLine("}");

        int next = afterThen;
        if (node.Otherwise is not null)
        {
            // afterThen is exactly where the else range begins.
            writer.AppendLine("else");
            writer.AppendLine("{");
            writer.Indent++;
            next = EmitNode(writer, node.Otherwise, afterThen);
            writer.Indent--;
            writer.AppendLine("}");
        }

        writer.AppendLine("__builder.CloseRegion();");

        return next;
    }

    private static int EmitForEach(IndentedWriter writer, ForEachNode node, int seq)
    {
        // seq is consumed by OpenRegion. The content template occupies [seq+1, seq+1+W(content)) and
        // those sequence numbers are re-emitted every iteration; SetKey carries per-item identity.
        writer.AppendLine($"__builder.OpenRegion({seq});");
        writer.AppendLine($"foreach (var {node.LoopVariableName} in {node.Source.ToCode()})");
        writer.AppendLine("{");
        writer.Indent++;
        // The key is threaded into the content's root element/component so SetKey is emitted
        // immediately after that frame opens, never after OpenRegion (see BCF3003).
        int next = EmitNode(writer, node.Content, seq + 1, node.Key.ToCode());
        writer.Indent--;
        writer.AppendLine("}");
        writer.AppendLine("__builder.CloseRegion();");
        return next;
    }

    /// <summary>
    /// Emits a composable expansion's locals and then its body. Reached only when the expansion is not
    /// foldable, that is when at least one local's initializer is not a compile-time constant: a fully
    /// constant expansion is absorbed into a markup frame by the fold check in <see cref="EmitNode"/> (a
    /// lone or root expansion) or <see cref="EmitChildren"/> (one among a sibling run), with its
    /// declarations dropped because constant initializers have no side effects. The body may still fold
    /// on its own here.
    /// </summary>
    private static int EmitExpansion(IndentedWriter writer, ExpansionNode node, int startSeq, string? key = null)
    {
        foreach (var local in node.Locals)
        {
            writer.AppendLine(
                $"{local.TypeName} {local.Name} = {local.Initializer.ToCode()};");
        }

        // Forward the key to the composable body's root element/component.
        return EmitNode(writer, node.Body, startSeq, key);
    }

    private static int EmitComponent(IndentedWriter writer, ComponentNode node, int seq, string? key = null)
    {
        // TypeName already carries the global:: prefix (fully qualified format).
        writer.AppendLine($"__builder.OpenComponent<{node.TypeName}>({seq});");
        if (key is not null)
            writer.AppendLine($"__builder.SetKey({key});");
        int next = seq + 1;
        foreach (var parameter in node.Parameters)
        {
            writer.AppendLine(
                $"__builder.AddComponentParameter({next}, \"{parameter.Name}\", {parameter.Value.ToCode()});");
            next++;
        }

        foreach (var slot in node.Slots)
        {
            // The lambda parameter deliberately SHADOWS the enclosing __builder. Every Emit* method
            // writes to the identifier `__builder`, so a distinct name (Razor uses __builder2/3) would
            // mean threading a builder name through all of them. Shadowing is legal and warning-free to
            // arbitrary depth, verified with nested slots, generated foreach loops, and local
            // declarations, on every LangVersion from 8 to 14. Do not "fix" it.
            switch (slot.Kind)
            {
                case ComponentSlotKind.NonGeneric:
                    writer.AppendLine(
                        $"__builder.AddComponentParameter({next}, \"{slot.Name}\", "
                            + $"({RenderFragmentType})((__builder) =>");
                    break;
                case ComponentSlotKind.GenericContextIgnored when slot.ContextTypeName is { } contextTypeName:
                    writer.AppendLine(
                        $"__builder.AddComponentParameter({next}, \"{slot.Name}\", "
                            + $"({RenderFragmentType}<{contextTypeName}>)((_) => (__builder) =>");
                    break;
                case ComponentSlotKind.GenericContextIgnored:
                    throw new InvalidOperationException(
                        $"A {nameof(ComponentSlotKind.GenericContextIgnored)} slot requires a context type.");
                case ComponentSlotKind.GenericContextual
                    when slot.ContextTypeName is { } contextTypeName
                        && slot.ContextVariableName is { } contextVariableName:
                    writer.AppendLine(
                        $"__builder.AddComponentParameter({next}, \"{slot.Name}\", "
                            + $"({RenderFragmentType}<{contextTypeName}>)"
                            + $"(({contextVariableName}) => (__builder) =>");
                    break;
                case ComponentSlotKind.GenericContextual:
                    throw new InvalidOperationException(
                        $"A {nameof(ComponentSlotKind.GenericContextual)} slot requires a context type and variable name.");
                default:
                    throw new NotSupportedException(
                        $"Emission for component slot kind '{slot.Kind}' is not yet implemented.");
            }
            writer.AppendLine("{");
            writer.Indent++;
            // Sequence numbering continues flatly from `next + 1`: a slot must not restart its own
            // sequence space. A slot's frames belong to the *child* component's frame list, and a host
            // that invokes the fragment directly (instead of passing it to AddContent) gets no isolating
            // region, so restarting at 0 collides with the host's own low numbers and remounts components
            // (measured). ARCHITECTURE.md §2.7 records this.
            int afterSlotContent = EmitNode(writer, slot.Content, next + 1);
            writer.Indent--;
            writer.AppendLine("}));");
            next = afterSlotContent;
        }

        writer.AppendLine("__builder.CloseComponent();");
        return next;
    }

    private static int EmitElement(IndentedWriter writer, ElementNode node, int seq, string? key = null)
    {
        writer.AppendLine($"__builder.OpenElement({seq}, \"{node.Tag}\");");
        if (key is not null)
            writer.AppendLine($"__builder.SetKey({key});");
        int next = seq + 1;
        next = EmitClassAttribute(writer, node.Classes, next);
        foreach (var attribute in node.Attributes)
        {
            var name = global::Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(attribute.Name, quote: true);
            writer.AppendLine($"__builder.AddAttribute({next}, {name}, {attribute.Value.ToCode()});");
            next++;
        }
        foreach (var e in node.Events)
        {
            var name = global::Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(e.Name, quote: true);
            writer.AppendLine(
                $"__builder.AddAttribute({next}, {name}, " +
                $"{EventCallbackFactory}.Create(this, {e.Handler.ToCode()}));");
            next++;
        }
        foreach (var bind in node.Bindings)
        {
            var attributeName =
                global::Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(bind.AttributeName, quote: true);
            var eventName =
                global::Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(bind.EventName, quote: true);
            writer.AppendLine($"__builder.AddAttribute({next}, {attributeName}, {bind.Value.ToCode()});");
            next++;
            // The framework's own CreateBinder overload for string annotates its setter parameter
            // Action<string?> defensively; the binder this template builds — the inverted getter, the
            // explicit-setter cast, CreateInferredBindSetter — is synthesized here and nowhere else, so
            // this is the one place that annotation can disagree with a non-nullable <value> or setter.
            // Measured against a real dispatch (BindRenderingTests, EmptyInput_DeliversEmptyStringNotNull):
            // an empty text input's oninput never actually delivers null, so there is no runtime defect
            // to fix, only this static mismatch to silence. Scoped to the one line it is about, not the
            // whole file: an author's own null assignment inside a transplanted Body expression is not
            // this binder, and must keep failing in the author's own file.
            writer.AppendLine("#pragma warning disable CS8601, CS8620");
            writer.AppendLine($"__builder.AddAttribute({next}, {eventName}, {bind.Binder.ToCode()});");
            writer.AppendLine("#pragma warning restore CS8601, CS8620");
            next++;
            // Blazor resynchronizes the DOM from this attribute when a re-render produces the value the
            // element already shows. Without it, a setter that normalizes or rejects the incoming value
            // leaves the element displaying the rejected text while the field holds something else.
            //
            // Only "value" and "checked" are named. EventFieldInfo.getFormFieldData sends back the
            // element's own value — checked on a checkbox — for an input, select or textarea, and null
            // for everything else, and RenderTreeUpdater.UpdateToMatchClientState writes that value into
            // whichever frame this names. A third attribute name is therefore dead on a custom element
            // and actively wrong on a form element, where it would overwrite an unrelated frame of the
            // retained tree and leave the real attribute stranded (#162).
            if (ResynchronizesFromDom(bind.AttributeName))
                writer.AppendLine($"__builder.SetUpdatesAttributeName({attributeName});");
        }
        next = EmitChildren(writer, node.Children, next);
        writer.AppendLine("__builder.CloseElement();");
        return next;
    }

    /// <summary>
    /// Whether Blazor's DOM resynchronization can act on <paramref name="attributeName"/>. These are the
    /// only two names <c>EventFieldInfo</c> can produce, so they are the only two worth recording.
    /// </summary>
    private static bool ResynchronizesFromDom(string attributeName) =>
        attributeName is "value" or "checked";

    private static int EmitTextContent(IndentedWriter writer, TextContentNode node, int seq)
    {
        writer.AppendLine($"__builder.AddContent({seq}, {node.Content.ToCode()});");
        return seq + 1;
    }

    private static int EmitFragment(IndentedWriter writer, FragmentNode node, int seq) =>
        EmitChildren(writer, node.Children, seq);

    private static int EmitRawMarkup(IndentedWriter writer, RawMarkupNode node, int seq)
    {
        writer.AppendLine($"__builder.AddMarkupContent({seq}, {node.Content.ToCode()});");
        return seq + 1;
    }

    private static int EmitRenderFragmentContent(
        IndentedWriter writer, RenderFragmentContentNode node, int seq)
    {
        writer.AppendLine($"__builder.AddContent({seq}, {node.Content.ToCode()});");
        return seq + 1;
    }

    /// <summary>
    /// Minimal indent-aware wrapper over a <see cref="StringBuilder"/>. Line endings come from
    /// <see cref="StringBuilder.AppendLine()"/> (<see cref="Environment.NewLine"/>) so generated
    /// output stays byte-identical to the previous manual indent threading.
    /// </summary>
    /// <remarks>
    /// <see cref="System.CodeDom.Compiler.IndentedTextWriter"/> is deliberately not used: System.CodeDom
    /// is outside the netstandard2.0 shared framework and is not bundled with the packaged analyzer, so
    /// referencing it would risk a <see cref="System.IO.FileNotFoundException"/> at analyzer load time.
    /// </remarks>
    private sealed class IndentedWriter
    {
        private const string IndentUnit = "    ";

        private readonly StringBuilder _sb = new();

        /// <summary>The current indentation depth, in units of four spaces.</summary>
        public int Indent { get; set; }

        /// <summary>Appends a blank line, without leading indentation.</summary>
        public void AppendLine() => _sb.AppendLine();

        /// <summary>Appends the current indentation followed by <paramref name="text"/> and a line break.</summary>
        public void AppendLine(string text)
        {
            AppendIndent();
            _sb.AppendLine(text);
        }

        /// <summary>Appends the current indentation followed by <paramref name="text"/>, without a line break.</summary>
        public void Append(string text)
        {
            AppendIndent();
            _sb.Append(text);
        }

        public override string ToString() => _sb.ToString();

        private void AppendIndent()
        {
            for (int i = 0; i < Indent; i++)
                _sb.Append(IndentUnit);
        }
    }
}
