using System;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Text;
using BlazorCodeFirst.Compiler.Generation;
using Microsoft.CodeAnalysis.Text;

namespace BlazorCodeFirst.Compiler;

/// <summary>Emits a <c>RenderView</c> override into the generated partial class.</summary>
internal static class RenderViewEmitter
{
    private const string RtbType =
        "global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder";

    private const string EventCallbackFactory =
        "global::Microsoft.AspNetCore.Components.EventCallback.Factory";

    /// <summary>
    /// The attribute-name prefix Blazor reads a <c>preventDefault</c> modifier from, the event's own name
    /// appended to it.
    /// </summary>
    /// <remarks>
    /// Written here rather than called through <c>AddEventPreventDefaultAttribute</c>, which is only an
    /// extension method producing exactly this <c>AddAttribute</c> call and which lives in
    /// <c>Microsoft.AspNetCore.Components.Web</c> — an assembly the shipped package deliberately does not
    /// reference (#23), and whether it should is a question #156 holds rather than one this channel may
    /// answer by accident. The cost is a framework-internal name in generated code with no compile-time
    /// tie to the version that defines it, and <c>EventModifierParityTests</c> is what buys that back: it
    /// reads this constant rather than transcribing it, so the two cannot drift (#368).
    /// </remarks>
    internal const string PreventDefaultAttributePrefix = "__internal_preventDefault_";

    /// <summary>The <c>stopPropagation</c> half; see <see cref="PreventDefaultAttributePrefix"/>.</summary>
    internal const string StopPropagationAttributePrefix = "__internal_stopPropagation_";

    /// <summary>
    /// A binding's <c>CreateBinder</c> call up to its setter argument, written as the static call it is.
    /// It is an extension method on <c>EventCallbackFactory</c>, and the generated file carries no
    /// <c>using</c> directives, so the instance spelling Razor uses
    /// (<c>EventCallback.Factory.CreateBinder(…)</c>) fails with CS1061 here. This is the same
    /// normalization <c>ExpressionTemplateFactory</c> applies to any extension method an author writes in
    /// instance syntax, for the same reason (<c>ARCHITECTURE.md</c> §2). Its sibling
    /// <see cref="EventCallbackFactory"/><c>.Create</c>, which the event channel emits, needs no such
    /// treatment because <c>Create</c> is an instance method — and the receiver both of them name is read
    /// from that one constant, so the two spellings cannot drift apart.
    /// </summary>
    private const string CreateBinderCall =
        "global::Microsoft.AspNetCore.Components.EventCallbackFactoryBinderExtensions.CreateBinder("
        + EventCallbackFactory + ", this, ";

    private const string RuntimeHelpers =
        "global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers";

    /// <summary>
    /// The converter a binding written with a culture formats its attribute value through. Overload
    /// resolution in the generated file picks the concrete overload for the bound type, which returns a
    /// <see langword="string"/> (a <see langword="bool"/> for <see langword="bool"/>), so the frame
    /// receives an already-formatted value and the formatting happens here, under the culture the call
    /// site wrote, rather than at render time under whichever culture that thread carries (#158, #307).
    /// </summary>
    private const string BindConverter =
        "global::Microsoft.AspNetCore.Components.BindConverter";

    private const string RenderFragmentType =
        "global::Microsoft.AspNetCore.Components.RenderFragment";

    /// <summary>
    /// The one BlazorCodeFirst runtime member generated code calls. Generated <c>RenderView</c> bodies live
    /// in the consumer's assembly, so the Opaque path cannot read <c>View</c>'s internal fragment field
    /// directly (<c>ARCHITECTURE.md</c> §3.2).
    /// </summary>
    private const string ViewRuntimeType = "global::BlazorCodeFirst.CompilerServices.ViewRuntime";

    public static SourceText Emit(ComponentModel model)
    {
        var writer = new IndentedWriter();
        writer.AppendLine("// <auto-generated/>");
        writer.AppendLine("#nullable enable");
        writer.AppendLine("#pragma warning disable CS0219");
        writer.AppendLine();

        if (model.Namespace is { } ns)
        {
            writer.AppendLine($"namespace {ns};");
            writer.AppendLine();
        }

        // A generic component's generated part must repeat the type-parameter list, or it declares a
        // different type and the override does not join the user's class (CS0115 + CS0534). Constraints
        // are omitted deliberately: they belong to the type parameter, so one declaration carrying them
        // is enough (verified), and reproducing them wrongly would reject correct user code.
        var typeParameters = model.TypeParameters.AsImmutableArray();
        var typeParameterList = typeParameters.Length == 0
            ? string.Empty
            : "<" + string.Join(", ", typeParameters) + ">";

        writer.AppendLine($"partial class {model.ClassName}{typeParameterList}");
        writer.AppendLine("{");
        writer.Indent++;
        writer.AppendLine($"protected override void RenderView({RtbType} __builder)");
        writer.AppendLine("{");
        writer.Indent++;

        EmitNode(writer, model.RootNode, startSeq: 0);

        writer.Indent--;
        writer.AppendLine("}");

        // The joins the body called, written after the method that calls them, from the widest call down
        // to two: each arity's body defers to the one below it when a term is null, and below two is a
        // term rather than a call. A class carrying no join writes none of this.
        for (int arity = writer.WidestClassJoin; arity >= 2; arity--)
        {
            writer.AppendLine();
            writer.AppendLine(ClassChannel.JoinHelperCode(arity));
        }

        writer.Indent--;
        writer.Append("}");

        return SourceText.From(writer.ToString(), Encoding.UTF8);
    }

    // ---------------------------------------------------------------------------
    // Node emission, returns the next available sequence number
    // ---------------------------------------------------------------------------

    /// <param name="key">
    /// When non-<see langword="null"/>, a key expression to apply to this node's root element/component
    /// frame via <c>SetKey</c> immediately after it opens. Supplied only by <see cref="EmitForEach"/> for
    /// the loop content root; the key is consumed by the first element/component and never propagated to
    /// children. Region-rooted nodes (<see cref="IfNode"/>, <see cref="ForEachNode"/>) never receive a
    /// non-<see langword="null"/> key because BCF3003 blocks region-rooted content from reaching emission.
    /// </param>
    private static int EmitNode(IndentedWriter writer, RenderNode node, int startSeq, string? key = null)
    {
        // A folded run is one AddMarkupContent frame, which SetKey cannot attach to. EmitForEach is the
        // only caller that passes a non-null key (for the loop content root), so this check is what keeps
        // a ForEach content root out of the fold; there is no separate predicate to keep in step
        // (ARCHITECTURE.md §2.7(D)).
        if (key is null
            && StaticMarkupSerializer.IsFoldable(node)
            && TryEmitFolded(writer, [node], startSeq, out var afterFold))
        {
            return afterFold;
        }

        return EmitUnfolded(writer, node, startSeq, key);
    }

    /// <summary>
    /// Dispatches <paramref name="node"/> to its emitter without attempting a fold, and returns the next
    /// available sequence number. Separate from <see cref="EmitNode"/> so that a caller which already knows
    /// folding is not on the table can say so instead of paying to rediscover it: <see cref="EmitChildren"/>
    /// reaches here for a run it has just seen declined, where a second attempt is not merely wasteful but
    /// provably futile — <see cref="StaticMarkupSerializer.WriteTo"/> sums the absorbed count over the run,
    /// so a run declined for absorbing fewer than two frames has every member absorbing fewer than two on
    /// its own.
    /// </summary>
    /// <param name="key">As <see cref="EmitNode"/>.</param>
    private static int EmitUnfolded(IndentedWriter writer, RenderNode node, int startSeq, string? key)
    {
        // Only three node kinds can receive a threaded key: the two that open a keyable frame and consume
        // it, and the expansion that forwards it to its body's root. Everything else is region-rooted or
        // frameless, and BCF3003 blocks region-rooted content from reaching emission at all, so a key
        // arriving at one of them means a keyable node was wired to this dispatch without updating that
        // contract. Asserted once here, where the split is already visible, rather than restated at each
        // arm that would otherwise take a key it cannot honour. The test guards the assertion rather than
        // riding inside it because the message is interpolated: as an argument it would be built on every
        // node in a DEBUG build, and only a ForEach content root ever arrives with a key.
        if (key is not null)
        {
            Debug.Assert(
                node is ElementNode or ComponentNode or ExpansionNode or TransplantedBlockNode,
                $"A key reached '{node.GetType().Name}', which opens no keyable frame; SetKey would be silently dropped.");
        }

        return node switch
        {
            IfNode ifNode => EmitIf(writer, ifNode, startSeq),
            ExpansionNode expansion => EmitExpansion(writer, expansion, startSeq, key),
            ForEachNode forEach => EmitForEach(writer, forEach, startSeq),
            ComponentNode component => EmitComponent(writer, component, startSeq, key),
            ElementNode element => EmitElement(writer, element, startSeq, key),
            TextContentNode text => EmitTextContent(writer, text, startSeq),
            FragmentNode fragment => EmitFragment(writer, fragment, startSeq),
            RawMarkupNode raw => EmitRawMarkup(writer, raw, startSeq),
            RenderFragmentContentNode fragmentContent =>
                EmitRenderFragmentContent(writer, fragmentContent, startSeq),
            OpaqueViewNode opaque => EmitOpaqueView(writer, opaque, startSeq),
            TransplantedBlockNode transplanted =>
                EmitTransplantedBlock(writer, transplanted, startSeq, key),
            _ => throw new NotSupportedException(
                $"Emission for '{node.GetType().Name}' is not yet implemented."),
        };
    }

    /// <summary>
    /// Emits a child list, coalescing maximal runs of consecutive foldable siblings into one
    /// <c>AddMarkupContent</c> frame each, and returns the next available sequence number. The run, not
    /// the subtree, is the fold unit: adjacent static siblings with nothing dynamic between them become
    /// one frame, which is what #142's measurement found the reduction actually comes from.
    /// </summary>
    private static int EmitChildren(IndentedWriter writer, EquatableArray<RenderNode> children, int seq)
    {
        var nodes = children.AsImmutableArray();
        var index = 0;
        while (index < nodes.Length)
        {
            if (!StaticMarkupSerializer.IsFoldable(nodes[index]))
            {
                seq = EmitNode(writer, nodes[index], seq);
                index++;
                continue;
            }

            var runEnd = index + 1;
            while (runEnd < nodes.Length && StaticMarkupSerializer.IsFoldable(nodes[runEnd]))
                runEnd++;

            var run = ImmutableArray.Create(nodes, index, runEnd - index);
            if (TryEmitFolded(writer, run, seq, out var afterFold))
            {
                seq = afterFold;
            }
            else
            {
                // Foldable but not worth folding: emit the run's nodes as they stand. Straight to
                // EmitUnfolded, because routing them back through EmitNode would walk each subtree for
                // IsFoldable again and re-serialize it into a StringBuilder only to decline a second time.
                for (var inner = index; inner < runEnd; inner++)
                    seq = EmitUnfolded(writer, nodes[inner], seq, key: null);
            }

            index = runEnd;
        }

        return seq;
    }

    /// <summary>
    /// Emits <paramref name="run"/> as one <c>AddMarkupContent</c> frame when doing so replaces at least
    /// two frames, and reports the next sequence number through <paramref name="next"/>. A run worth one
    /// frame is left alone: folding it would change the shape without reducing anything.
    /// </summary>
    /// <param name="run">
    /// Nodes that all satisfy <see cref="StaticMarkupSerializer.IsFoldable"/>. Both callers have already
    /// established that — <see cref="EmitChildren"/> because partitioning into runs is how it finds them,
    /// <see cref="EmitNode"/> by testing the single node — so this does not re-derive it. Passing an
    /// unfoldable node throws out of the serializer rather than being quietly declined.
    /// </param>
    /// <remarks>
    /// Whether a fold pays for itself is only known after serializing the run, so the losing case is
    /// unavoidable work. What it need not include is the markup string: the count comes back from
    /// <see cref="StaticMarkupSerializer.WriteTo"/> while the text is still in the builder, and a run that
    /// cannot win is abandoned there. This matters because the losing case is not rare — a lone static text
    /// child absorbs exactly one frame, so every one of them is attempted, declined, and then emitted as a
    /// frame by its caller.
    /// </remarks>
    private static bool TryEmitFolded(
        IndentedWriter writer, ImmutableArray<RenderNode> run, int seq, out int next)
    {
        next = seq;

        var markup = new StringBuilder();
        if (StaticMarkupSerializer.WriteTo(markup, run) < 2)
            return false;

        var literal = global::Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(
            markup.ToString(), quote: true);
        writer.AppendLine($"__builder.AddMarkupContent({seq}, {literal});");
        next = seq + 1;
        return true;
    }

    /// <summary>
    /// Emits the folded <c>class</c> attribute for a decorated element and returns the next sequence
    /// number. All <c>.Class</c> decorations collapse into one attribute frame (ARCHITECTURE.md §2.7(A)),
    /// and <see cref="ClassChannel.JoinAsCode"/> writes the value they collapse to. What this method
    /// decides is the framing: one frame however many decorations there are, and no frame at all when
    /// there are none, which is why the empty case is tested here rather than left to the join. A
    /// decoration whose value folds away is still a decoration, so a frame is emitted for it too (#234).
    /// </summary>
    private static int EmitClassAttribute(IndentedWriter writer, EquatableArray<ExpressionTemplate> classes, int seq)
    {
        if (classes.Length == 0)
            return seq;

        string value = ClassChannel.JoinAsCode(classes, out int joinArity);
        if (joinArity > writer.WidestClassJoin)
            writer.WidestClassJoin = joinArity;

        writer.AppendLine(
            $"__builder.AddAttribute({seq}, \"{ClassChannel.AttributeName}\", {value});");
        return seq + 1;
    }

    private static int EmitIf(IndentedWriter writer, IfNode node, int seq)
    {
        // seq is consumed by OpenRegion.
        // then  branch occupies [seq+1, seq+1+W(then)).
        // else  branch occupies [seq+1+W(then), seq+1+W(then)+W(else)).
        // Both branches are reserved whichever one runs, so a following sibling receives a sequence
        // independent of the condition. The cursor after the last emitted branch *is* that reservation:
        // with no else, `afterThen` already sits at the end of the then range.
        int thenStart = seq + 1;

        writer.AppendLine($"__builder.OpenRegion({seq});");
        writer.AppendLine($"if ({node.ConditionExpression.ToCode()})");
        writer.AppendLine("{");
        writer.Indent++;
        int afterThen = EmitNode(writer, node.Then, thenStart);
        writer.Indent--;
        writer.AppendLine("}");

        int next = afterThen;
        if (node.Otherwise is not null)
        {
            // afterThen is exactly where the else range begins.
            writer.AppendLine("else");
            writer.AppendLine("{");
            writer.Indent++;
            next = EmitNode(writer, node.Otherwise, afterThen);
            writer.Indent--;
            writer.AppendLine("}");
        }

        writer.AppendLine("__builder.CloseRegion();");

        return next;
    }

    private static int EmitForEach(IndentedWriter writer, ForEachNode node, int seq)
    {
        // seq is consumed by OpenRegion. The content template occupies [seq+1, seq+1+W(content)) and
        // those sequence numbers are re-emitted every iteration; SetKey carries per-item identity.
        writer.AppendLine($"__builder.OpenRegion({seq});");
        writer.AppendLine($"foreach (var {node.LoopVariableName} in {node.Source.ToCode()})");
        writer.AppendLine("{");
        writer.Indent++;
        // The key is threaded into the content's root element/component so SetKey is emitted
        // immediately after that frame opens, never after OpenRegion (see BCF3003). A declined key
        // threads nothing, which also makes the content root eligible for the fold in EmitNode: that
        // check turns on the threaded key and nothing else, so no second predicate says so (#172).
        int next = EmitNode(writer, node.Content, seq + 1, node.Key?.ToCode());
        writer.Indent--;
        writer.AppendLine("}");
        writer.AppendLine("__builder.CloseRegion();");
        return next;
    }

    /// <summary>
    /// Emits a view part expansion's locals and then its body. Reached only when the expansion is not
    /// foldable, that is when at least one local's initializer is not a compile-time constant: a fully
    /// constant expansion is absorbed into a markup frame by the fold check in <see cref="EmitNode"/> (a
    /// lone or root expansion) or <see cref="EmitChildren"/> (one among a sibling run), with its
    /// declarations dropped because constant initializers have no side effects. The body may still fold
    /// on its own here.
    /// </summary>
    private static int EmitExpansion(IndentedWriter writer, ExpansionNode node, int startSeq, string? key = null)
    {
        foreach (var local in node.Locals)
        {
            writer.AppendLine(
                $"{local.TypeName} {local.Name} = {local.Initializer.ToCode()};");
        }

        // Forward the key to the view part body's root element/component.
        return EmitNode(writer, node.Body, startSeq, key);
    }

    private static int EmitComponent(IndentedWriter writer, ComponentNode node, int seq, string? key = null)
    {
        // TypeName already carries the global:: prefix (fully qualified format).
        writer.AppendLine($"__builder.OpenComponent<{node.TypeName}>({seq});");
        EmitKey(writer, node.Key, key);
        int next = seq + 1;
        foreach (var parameter in node.Parameters)
        {
            // Cast to the type the call site resolved. AddComponentParameter takes object?, so the value
            // loses the target type it was written against: a lambda with no natural type does not bind
            // here at all, and one whose natural type is not the declared type binds as that type and
            // fails when the renderer assigns the property (#377).
            //
            // Razor writes two spellings in this position, the cast for a delegate-typed parameter and
            // RuntimeHelpers.TypeCheck<T> for the rest, and that split is not forced by C#: both bind every
            // shape this surface admits (measured). One spelling is written here rather than two, because a
            // second would need a rule saying which value gets which, and nothing measured supplies one.
            // The cast is that spelling. It is what this file already writes wherever a transplanted
            // expression has to be given its type — the bind setter's Action<T>, a slot's RenderFragment,
            // the .Ref capture — and it names the type without reaching for a framework helper.
            var value = parameter.ValueTypeName is { } typeName
                ? $"({typeName})({parameter.Value.ToCode()})"
                : parameter.Value.ToCode();
            writer.AppendLine(
                $"__builder.AddComponentParameter({next}, \"{parameter.Name}\", {value});");
            next++;
        }

        foreach (var slot in node.Slots)
        {
            // The lambda parameter deliberately SHADOWS the enclosing __builder. Every Emit* method
            // writes to the identifier `__builder`, so a distinct name (Razor uses __builder2/3) would
            // mean threading a builder name through all of them. Shadowing is legal and warning-free to
            // arbitrary depth, verified with nested slots, generated foreach loops, and local
            // declarations, on every LangVersion from 8 to 14. Do not "fix" it.
            switch (slot.Kind)
            {
                case ComponentSlotKind.NonGeneric:
                    writer.AppendLine(
                        $"__builder.AddComponentParameter({next}, \"{slot.Name}\", "
                            + $"({RenderFragmentType})((__builder) =>");
                    break;
                case ComponentSlotKind.GenericContextIgnored when slot.ContextTypeName is { } contextTypeName:
                    writer.AppendLine(
                        $"__builder.AddComponentParameter({next}, \"{slot.Name}\", "
                            + $"({RenderFragmentType}<{contextTypeName}>)((_) => (__builder) =>");
                    break;
                case ComponentSlotKind.GenericContextIgnored:
                    throw new InvalidOperationException(
                        $"A {nameof(ComponentSlotKind.GenericContextIgnored)} slot requires a context type.");
                case ComponentSlotKind.GenericContextual
                    when slot.ContextTypeName is { } contextTypeName
                        && slot.ContextVariableName is { } contextVariableName:
                    writer.AppendLine(
                        $"__builder.AddComponentParameter({next}, \"{slot.Name}\", "
                            + $"({RenderFragmentType}<{contextTypeName}>)"
                            + $"(({contextVariableName}) => (__builder) =>");
                    break;
                case ComponentSlotKind.GenericContextual:
                    throw new InvalidOperationException(
                        $"A {nameof(ComponentSlotKind.GenericContextual)} slot requires a context type and variable name.");
                default:
                    throw new NotSupportedException(
                        $"Emission for component slot kind '{slot.Kind}' is not yet implemented.");
            }
            writer.AppendLine("{");
            writer.Indent++;
            // Sequence numbering continues flatly from `next + 1`: a slot must not restart its own
            // sequence space. A slot's frames belong to the *child* component's frame list, and a host
            // that invokes the fragment directly (instead of passing it to AddContent) gets no isolating
            // region, so restarting at 0 collides with the host's own low numbers and remounts components
            // (measured). ARCHITECTURE.md §2.7 records this.
            int afterSlotContent = EmitNode(writer, slot.Content, next + 1);
            writer.Indent--;
            writer.AppendLine("}));");
            next = afterSlotContent;
        }

        // After every parameter frame, scalar and slot alike, and not merely after the scalars: a slot is
        // an AddComponentParameter too, and AssertCanAddComponentParameter reads the last non-attribute
        // frame's type, so a render mode written between the two would make the next slot throw. It takes
        // no sequence number, so `next` is untouched by it (ARCHITECTURE.md §2.7(E)).
        if (node.RenderMode is { } renderMode)
            writer.AppendLine($"__builder.AddComponentRenderMode({renderMode.ToCode()});");

        // After the render mode, not before. The renderer finds a caller-specified mode by scanning the
        // component's frames for the first ComponentRenderMode, and putting the capture frame in front of
        // it puts a frame of another type in that scan's way for no gain. Both orders are legal to the
        // builder, so this is the order chosen rather than the order forced.
        if (node.Ref is { } componentCapture)
        {
            // The framework hands the action an object; the surface takes an Action<TComponent> because
            // this type is known here. The cast on the delegate is what lets a lambda written in argument
            // position be invoked at all, the same reason a synchronous bind setter carries one.
            writer.AppendLine(
                $"__builder.AddComponentReferenceCapture({next}, __value => "
                    + $"((global::System.Action<{node.TypeName}>)({componentCapture.ToCode()}))"
                    + $"(({node.TypeName})__value));");
            next++;
        }

        writer.AppendLine("__builder.CloseComponent();");
        return next;
    }

    /// <summary>
    /// One event modifier's call, or nothing when the call site wrote no modifier.
    /// </summary>
    /// <remarks>
    /// A written <c>false</c> still emits. The frame it would produce is dropped by the framework, but a
    /// sequence number belongs to the emitted call rather than to the resulting frame, which is the rule
    /// Appendix D already records for <c>.Attr(name, false)</c>. That is what keeps the width of an element a
    /// function of the decorations written on it rather than of the values they carry (#234).
    /// </remarks>
    /// <summary>
    /// Both modifiers of one event, in the order the emitter fixes for them.
    /// </summary>
    /// <remarks>
    /// A fixed order rather than the chain's: the two are independent of each other, and one order has to
    /// be chosen so that the sequence numbers are a function of the model alone. Written once and called
    /// from both the event channel and the binding channel, so that order is one rule in one place rather
    /// than two copies that can drift apart with nothing failing (#370).
    /// </remarks>
    private static int EmitEventModifiers(
        IndentedWriter writer,
        string eventName,
        ExpressionTemplate? preventDefault,
        ExpressionTemplate? stopPropagation,
        int seq)
    {
        seq = EmitEventModifier(writer, PreventDefaultAttributePrefix, eventName, preventDefault, seq);
        return EmitEventModifier(writer, StopPropagationAttributePrefix, eventName, stopPropagation, seq);
    }

    private static int EmitEventModifier(
        IndentedWriter writer, string prefix, string eventName, ExpressionTemplate? value, int seq)
    {
        if (value is null)
            return seq;

        var name = global::Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(
            prefix + eventName, quote: true);
        writer.AppendLine($"__builder.AddAttribute({seq}, {name}, {value.ToCode()});");
        return seq + 1;
    }

    private static int EmitElement(IndentedWriter writer, ElementNode node, int seq, string? key = null)
    {
        // Escaped like the attribute, event and modifier names below it, and for the same reason: a
        // constant string is not a C# literal, and the two part company exactly where the author wrote
        // an escape. BCF3009 rejects every tag whose spelling this would rescue, so nothing reaches here
        // needing it today; it stays because the invariant is the emitter's own, and a caller filtered
        // by an analyzer in another file is not the same thing as a tag that cannot be misread (#388).
        var tag = global::Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(node.Tag, quote: true);
        writer.AppendLine($"__builder.OpenElement({seq}, {tag});");
        EmitKey(writer, node.Key, key);
        int next = seq + 1;
        next = EmitClassAttribute(writer, node.Classes, next);
        foreach (var attribute in node.Attributes)
        {
            var name = global::Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(attribute.Name, quote: true);
            writer.AppendLine(
                $"__builder.AddAttribute({next}, {name}, {attribute.Value.ToAttributeValueCode()});");
            next++;
        }
        foreach (var e in node.Events)
        {
            var name = global::Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(e.Name, quote: true);
            // The type argument the surface call resolved to, written out rather than left to inference.
            // `Create` is overloaded and the handler arrives here without the parameter type that gave it
            // context at the call site, so a method group has nothing to infer TValue from and an untyped
            // lambda parameter binds as object — both CS1503s in a file the author did not write (#371).
            // Naming TValue answers every spelling the surface admits at once, which is what Razor's own
            // output does for a typed handler (measured).
            var argsType = e.ArgsTypeName is null ? string.Empty : $"<{e.ArgsTypeName}>";
            writer.AppendLine(
                $"__builder.AddAttribute({next}, {name}, " +
                $"{EventCallbackFactory}.Create{argsType}(this, {e.Handler.ToCode()}));");
            next++;
            next = EmitEventModifiers(writer, e.Name, e.PreventDefault, e.StopPropagation, next);
        }
        foreach (var bind in node.Bindings)
        {
            var attributeName =
                global::Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(bind.AttributeName, quote: true);
            var eventName =
                global::Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(bind.EventName, quote: true);
            // The raw value and the attribute's value part company once a culture is written: the binder
            // takes the raw one, because CreateBinder's existingValue is the bound field and not the text
            // the element shows, while the attribute frame takes the formatted string. The two were the
            // same string before #307, which is why Binder() used to be handed the attribute's.
            //
            // Both are built once and threaded, for the reason Binder's own <param> gives about the
            // value: reading them again would rebuild the same strings. The tail is also the only test
            // of whether this binding formats at all, so asking it here and asking Binder to ask it
            // again would be two places encoding one rule.
            var value = bind.Value.ToCode();
            var tail = FormatAndCulture(bind);
            var attributeValue = tail.Length == 0 ? value : $"{BindConverter}.FormatValue({value}{tail})";
            writer.AppendLine($"__builder.AddAttribute({next}, {attributeName}, {attributeValue});");
            next++;
            // The framework's own CreateBinder overload for string annotates its setter parameter
            // Action<string?> defensively; the binder Binder() writes — the inverted getter, the
            // explicit-setter cast, CreateInferredBindSetter — is synthesized there and nowhere else, so
            // this is the one place that annotation can disagree with a non-nullable <value> or setter.
            // The suppression and the text it applies to are owned by the same layer, which is what #195
            // was about: a binder shape decided elsewhere could leave this stale with nothing failing.
            // Measured against a real dispatch (BindRenderingTests, EmptyInput_DeliversEmptyStringNotNull):
            // an empty text input's oninput never actually delivers null, so there is no runtime defect
            // to fix, only this static mismatch to silence. Scoped to the one line it is about, not the
            // whole file: an author's own null assignment inside a transplanted Body expression is not
            // this binder, and must keep failing in the author's own file.
            writer.AppendLine("#pragma warning disable CS8601, CS8620");
            writer.AppendLine($"__builder.AddAttribute({next}, {eventName}, {Binder(bind, value, tail)});");
            writer.AppendLine("#pragma warning restore CS8601, CS8620");
            next++;
            // Blazor resynchronizes the DOM from this attribute when a re-render produces the value the
            // element already shows. Without it, a setter that normalizes or rejects the incoming value
            // leaves the element displaying the rejected text while the field holds something else.
            //
            // Only "value" and "checked" are named. EventFieldInfo.getFormFieldData sends back the
            // element's own value — checked on a checkbox — for an input, select or textarea, and null
            // for everything else, and RenderTreeUpdater.UpdateToMatchClientState writes that value into
            // whichever frame this names. A third attribute name is therefore dead on a custom element
            // and actively wrong on a form element, where it would overwrite an unrelated frame of the
            // retained tree and leave the real attribute stranded (#162).
            if (ResynchronizesFromDom(bind.AttributeName))
                writer.AppendLine($"__builder.SetUpdatesAttributeName({attributeName});");
            // After SetUpdatesAttributeName and not between it and the event frame. That call records into
            // the immediately preceding attribute frame, so a modifier written in between would take the
            // resynchronized name onto itself and leave the binding's event frame without one (#370).
            next = EmitEventModifiers(
                writer, bind.EventName, bind.PreventDefault, bind.StopPropagation, next);
        }
        // After every attribute, event and binding frame, and before .Ref/the children. AddNamedEvent takes
        // no sequence argument, so `next` is untouched by it (ARCHITECTURE.md §2.7(E)).
        if (node.FormName is { } formName)
            writer.AppendLine($"__builder.AddNamedEvent(\"onsubmit\", {formName.ToCode()});");

        // After every attribute, event and binding frame, and before the children. Both halves are forced:
        // AssertCanAddAttribute reads the last non-attribute frame's type, so an attribute written after
        // this would throw, and Blazor's diff reads an element's capture frame as part of its attribute
        // range, so a capture written after the children would fall outside it (ARCHITECTURE.md §2.7(E)).
        if (node.Ref is { } elementCapture)
        {
            writer.AppendLine(
                $"__builder.AddElementReferenceCapture({next}, {elementCapture.ToCode()});");
            next++;
        }

        next = EmitChildren(writer, node.Children, next);
        writer.AppendLine("__builder.CloseElement();");
        return next;
    }

    /// <summary>
    /// Writes the <c>SetKey</c> for a frame that has just opened, from the two channels that can supply
    /// one: the node's own <c>.Key</c> decoration and the key an enclosing <c>ForEach</c> threaded into its
    /// content root. Consumes no sequence number, so it reports nothing back to the caller's arithmetic.
    /// </summary>
    /// <remarks>
    /// The two are never both present. <c>SetKey</c> writes into the open frame, so a second call would
    /// overwrite the first, and BCF3032 refuses that pair at the template layer before emission is reached.
    /// Asserted rather than resolved by precedence: a precedence rule here would be a second answer to a
    /// question the diagnostic has already settled, and the two would be free to disagree.
    /// </remarks>
    private static void EmitKey(IndentedWriter writer, ExpressionTemplate? own, string? threaded)
    {
        Debug.Assert(
            own is null || threaded is null,
            "A node carries both its own .Key and a ForEach key; BCF3032 should have refused this pair.");

        if ((own?.ToCode() ?? threaded) is { } key)
            writer.AppendLine($"__builder.SetKey({key});");
    }

    /// <summary>
    /// Whether Blazor's DOM resynchronization can act on <paramref name="attributeName"/>. These are the
    /// only two names <c>EventFieldInfo</c> can produce, so they are the only two worth recording.
    /// </summary>
    private static bool ResynchronizesFromDom(string attributeName) =>
        attributeName is "value" or "checked";

    /// <summary>
    /// The <c>CreateBinder</c> call a binding's event frame carries: the setter in whichever of its three
    /// shapes the binding records, and <paramref name="value"/> as the current value, followed by the
    /// format and culture the binding was written with. All three shapes pass the current value in the
    /// same position and all three are one frame, so the shape changes nothing the sequence arithmetic
    /// above depends on.
    /// </summary>
    /// <param name="value">
    /// The bound value's code, raw — <em>not</em> the string the attribute frame received, which a
    /// binding written with a culture has already put through <c>FormatValue</c>. <c>existingValue</c> is
    /// the bound field, not the text the element shows. Passed in rather than read again from
    /// <see cref="BindTemplate.Value"/>, which would rebuild the same string.
    /// </param>
    /// <param name="tail">
    /// The <c>format:</c> and <c>culture:</c> arguments, from <see cref="FormatAndCulture"/>. Passed in
    /// for the same reason <paramref name="value"/> is, and because the caller has already asked the same
    /// question of it: an empty tail is what tells the attribute frame not to format.
    /// </param>
    /// <remarks>
    /// Assembled here rather than in the analyzer, beside the event channel's <c>Create</c> — the same
    /// factory call for the same job — and inside the suppression the caller writes for it. The analyzer
    /// supplies the facts it alone can read and nothing more (#195).
    /// <para>
    /// The cast on a synchronous setter is required: a lambda written in an argument position has no
    /// natural type, and <c>CreateBinder</c>'s own overloads cannot pick one for it once the setter has
    /// travelled through a template. The asynchronous shape needs none, because
    /// <c>CreateInferredBindSetter</c> infers it.
    /// </para>
    /// </remarks>
    private static string Binder(BindTemplate bind, string value, string tail)
    {
        // CreateBinder(this, __value => <value> = __value, <value>[, format:][, culture:])
        if (bind.Setter is not { } setter)
            return $"{CreateBinderCall}__value => {value} = __value, {value}{tail})";

        var setterCode = setter.ToCode();

        return bind.SetterIsAsynchronous
            // CreateBinder(this, RuntimeHelpers.CreateInferredBindSetter(callback: <setter>, value: <value>), <value>)
            ? $"{CreateBinderCall}{RuntimeHelpers}.CreateInferredBindSetter("
                + $"callback: {setterCode}, value: {value}), {value}{tail})"
            // CreateBinder(this, (Action<T>)(<setter>), <value>)
            : $"{CreateBinderCall}(global::System.Action<{bind.ValueTypeName}>)({setterCode}), "
                + $"{value}{tail})";
    }

    /// <summary>
    /// The trailing <c>format:</c> and <c>culture:</c> arguments that <c>FormatValue</c> and
    /// <c>CreateBinder</c> share, or the empty string for a binding that carries neither.
    /// </summary>
    /// <remarks>
    /// Named rather than positional. Both framework methods declare their culture optional, so a
    /// positional format would sit where a reader of the generated file has to count parameters to tell
    /// the two apart. One helper for both calls because the two must agree: a format the attribute value
    /// was written with and the binder was not would format one direction of the round trip and parse the
    /// other differently.
    /// </remarks>
    private static string FormatAndCulture(BindTemplate bind)
    {
        if (bind.Culture is not { } culture)
            return string.Empty;

        var format = bind.Format is { } f ? $", format: {f.ToCode()}" : string.Empty;
        return $"{format}, culture: {culture.ToCode()}";
    }

    private static int EmitTextContent(IndentedWriter writer, TextContentNode node, int seq)
    {
        writer.AppendLine($"__builder.AddContent({seq}, {node.Content.ToCode()});");
        return seq + 1;
    }

    private static int EmitFragment(IndentedWriter writer, FragmentNode node, int seq) =>
        EmitChildren(writer, node.Children, seq);

    private static int EmitRawMarkup(IndentedWriter writer, RawMarkupNode node, int seq)
    {
        writer.AppendLine($"__builder.AddMarkupContent({seq}, {node.Content.ToCode()});");
        return seq + 1;
    }

    /// <summary>
    /// Emits one <c>AddContent(seq, RenderFragment?)</c> frame. No OpenRegion: Blazor opens a region for
    /// the fragment itself, which is what keeps its internal sequence numbers away from ours, and a
    /// <see langword="null"/> fragment appends no frame at all — so neither caller needs a null test.
    /// </summary>
    private static int EmitFragmentFrame(IndentedWriter writer, string fragmentCode, int seq)
    {
        writer.AppendLine($"__builder.AddContent({seq}, {fragmentCode});");
        return seq + 1;
    }

    private static int EmitRenderFragmentContent(
        IndentedWriter writer, RenderFragmentContentNode node, int seq) =>
        EmitFragmentFrame(writer, node.Content.ToCode(), seq);

    /// <summary>
    /// Emits an Opaque call: the same frame, carrying the fragment the returned <c>View</c> holds rather
    /// than one the author supplied directly.
    /// </summary>
    private static int EmitOpaqueView(IndentedWriter writer, OpaqueViewNode node, int seq) =>
        EmitFragmentFrame(writer, $"{ViewRuntimeType}.FragmentOf({node.Call.ToCode()})", seq);

    /// <summary>
    /// Emits the author's transplanted statements, then the content they lead into. The key is forwarded
    /// to the content's root frame, exactly as <see cref="EmitExpansion"/> forwards it past its locals.
    /// </summary>
    /// <remarks>
    /// Written verbatim rather than line by line. A statement can span lines — a raw string literal, a
    /// chained call — and re-indenting the interior would change what a verbatim literal holds.
    /// </remarks>
    private static int EmitTransplantedBlock(
        IndentedWriter writer, TransplantedBlockNode node, int startSeq, string? key)
    {
        writer.AppendLine(node.Statements.ToCode());

        return EmitNode(writer, node.Content, startSeq, key);
    }

    /// <summary>
    /// One emission's output and the state that spans it: an indent-aware wrapper over a
    /// <see cref="StringBuilder"/>, plus what the end of the emission needs to know about its own middle.
    /// Line endings come from <see cref="StringBuilder.AppendLine()"/>
    /// (<see cref="Environment.NewLine"/>) so generated output stays byte-identical to the previous
    /// manual indent threading.
    /// </summary>
    /// <remarks>
    /// <see cref="System.CodeDom.Compiler.IndentedTextWriter"/> is deliberately not used: System.CodeDom
    /// is outside the netstandard2.0 shared framework and is not bundled with the packaged analyzer, so
    /// referencing it would risk a <see cref="System.IO.FileNotFoundException"/> at analyzer load time.
    /// </remarks>
    private sealed class IndentedWriter
    {
        private const string IndentUnit = "    ";

        private readonly StringBuilder _sb = new();

        /// <summary>The current indentation depth, in units of four spaces.</summary>
        public int Indent { get; set; }

        /// <summary>
        /// The widest class-channel join this emission has written a call to, or zero when it has written
        /// none. Read once the body is complete, to write the helper bodies those calls need.
        /// </summary>
        /// <remarks>
        /// Emission state rather than text, kept here because the writer is the one object already
        /// threaded through every emit method. The alternative is a second walk of the model to find the
        /// joins, and that walk would have to re-derive which terms survive folding — a second reading of
        /// <see cref="ClassChannel.JoinAsCode"/>'s rule, free to disagree with the first.
        /// </remarks>
        public int WidestClassJoin { get; set; }

        /// <summary>Appends a blank line, without leading indentation.</summary>
        public void AppendLine() => _sb.AppendLine();

        /// <summary>Appends the current indentation followed by <paramref name="text"/> and a line break.</summary>
        public void AppendLine(string text)
        {
            AppendIndent();
            _sb.AppendLine(text);
        }

        /// <summary>Appends the current indentation followed by <paramref name="text"/>, without a line break.</summary>
        public void Append(string text)
        {
            AppendIndent();
            _sb.Append(text);
        }

        public override string ToString() => _sb.ToString();

        private void AppendIndent()
        {
            for (int i = 0; i < Indent; i++)
                _sb.Append(IndentUnit);
        }
    }
}
