using System;
using System.Diagnostics;
using System.Linq;
using System.Text;
using BlazorCompose.Compiler.Generation;
using Microsoft.CodeAnalysis.Text;

namespace BlazorCompose.Compiler;

/// <summary>Emits a <c>RenderView</c> override into the generated partial class.</summary>
internal static class RenderViewEmitter
{
    private const string RtbType =
        "global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder";

    private const string EventCallbackFactory =
        "global::Microsoft.AspNetCore.Components.EventCallback.Factory";

    public static SourceText Emit(ComponentModel model)
    {
        var writer = new IndentedWriter();
        writer.AppendLine("// <auto-generated/>");
        writer.AppendLine("#nullable enable");
        writer.AppendLine("#pragma warning disable CS0219");
        writer.AppendLine();

        if (model.Namespace is { } ns)
        {
            writer.AppendLine($"namespace {ns};");
            writer.AppendLine();
        }

        writer.AppendLine($"partial class {model.ClassName}");
        writer.AppendLine("{");
        writer.Indent++;
        writer.AppendLine($"protected override void RenderView({RtbType} __builder)");
        writer.AppendLine("{");
        writer.Indent++;

        EmitNode(writer, model.RootNode, startSeq: 0);

        writer.Indent--;
        writer.AppendLine("}");
        writer.Indent--;
        writer.Append("}");

        return SourceText.From(writer.ToString(), Encoding.UTF8);
    }

    // ---------------------------------------------------------------------------
    // Node emission — returns the next available sequence number
    // ---------------------------------------------------------------------------

    /// <param name="key">
    /// When non-<see langword="null"/>, a key expression to apply to this node's root element/component
    /// frame via <c>SetKey</c> immediately after it opens. Supplied only by <see cref="EmitForEach"/> for
    /// the loop content root; the key is consumed by the first element/component and never propagated to
    /// children. Region-rooted nodes (<see cref="IfNode"/>, <see cref="ForEachNode"/>) never receive a
    /// non-<see langword="null"/> key because BC3003 blocks region-rooted content from reaching emission.
    /// </param>
    private static int EmitNode(IndentedWriter writer, RenderNode node, int startSeq, string? key = null) =>
        node switch
        {
            IfNode ifNode => EmitIf(writer, ifNode, startSeq, key),
            ExpansionNode expansion => EmitExpansion(writer, expansion, startSeq, key),
            ForEachNode forEach => EmitForEach(writer, forEach, startSeq, key),
            ComponentNode component => EmitComponent(writer, component, startSeq, key),
            ElementNode element => EmitElement(writer, element, startSeq, key),
            TextContentNode text => EmitTextContent(writer, text, startSeq),
            FragmentNode fragment => EmitFragment(writer, fragment, startSeq, key),
            RawMarkupNode raw => EmitRawMarkup(writer, raw, startSeq, key),
            RenderFragmentContentNode fragmentContent =>
                EmitRenderFragmentContent(writer, fragmentContent, startSeq, key),
            _ => throw new NotSupportedException(
                $"Emission for '{node.GetType().Name}' is not yet implemented."),
        };

    /// <summary>
    /// Emits the folded <c>class</c> attribute for a decorated element and returns the next sequence
    /// number. All <c>.Class</c> decorations collapse into one attribute frame (ARCHITECTURE.md §2.7(A)):
    /// a single class is emitted verbatim; N≥2 classes are concatenated as <c>(e0) + " " + (e1) + …</c>
    /// with each expression parenthesized so operator precedence (e.g. a ternary or <c>??</c>) is
    /// preserved. When every class is a string literal the C# compiler constant-folds this to one string.
    /// When there is no decoration, no frame is emitted and the sequence is unchanged.
    /// </summary>
    private static int EmitClassAttribute(IndentedWriter writer, EquatableArray<ExpressionTemplate> classes, int seq)
    {
        if (classes.Length == 0)
            return seq;

        var array = classes.AsImmutableArray();
        string value = array.Length == 1
            ? array[0].ToCode()
            : string.Join(" + \" \" + ", array.Select(static c => $"({c.ToCode()})"));

        writer.AppendLine($"__builder.AddAttribute({seq}, \"class\", {value});");
        return seq + 1;
    }

    private static int EmitIf(IndentedWriter writer, IfNode node, int seq, string? key = null)
    {
        // Region-rooted nodes never carry a threaded key: BC3003 blocks region-rooted content from
        // reaching emission, so a non-null key here would mean a keyable node was wired to this branch
        // without updating that contract. Fail fast in tests instead of silently dropping SetKey.
        Debug.Assert(key is null, $"{nameof(EmitIf)} does not support a threaded key; SetKey would be silently dropped.");

        // seq is consumed by OpenRegion.
        // then  branch occupies [seq+1, seq+1+W(then)).
        // else  branch occupies [seq+1+W(then), seq+1+W(then)+W(else)).
        // The total reservation equals SequenceAllocator.Width(node) so that sibling nodes
        // always receive a sequence that is independent of which branch executes at runtime.
        int thenStart = seq + 1;

        writer.AppendLine($"__builder.OpenRegion({seq});");
        writer.AppendLine($"if ({node.ConditionExpression.ToCode()})");
        writer.AppendLine("{");
        writer.Indent++;
        int afterThen = EmitNode(writer, node.Then, thenStart);
        writer.Indent--;
        writer.AppendLine("}");

        if (node.Otherwise is not null)
        {
            // afterThen == seq+1+Width(then) which is exactly where the else range begins.
            writer.AppendLine("else");
            writer.AppendLine("{");
            writer.Indent++;
            EmitNode(writer, node.Otherwise, afterThen);
            writer.Indent--;
            writer.AppendLine("}");
        }

        writer.AppendLine("__builder.CloseRegion();");

        return seq + SequenceAllocator.Width(node);
    }

    private static int EmitForEach(IndentedWriter writer, ForEachNode node, int seq, string? key = null)
    {
        // Region-rooted nodes never carry a threaded key: BC3003 blocks region-rooted content from
        // reaching emission, so a non-null key here would mean a keyable node was wired to this branch
        // without updating that contract. Fail fast in tests instead of silently dropping SetKey.
        Debug.Assert(key is null, $"{nameof(EmitForEach)} does not support a threaded key; SetKey would be silently dropped.");

        // seq is consumed by OpenRegion. The content template occupies [seq+1, seq+1+W(content)) and
        // those sequence numbers are re-emitted every iteration; SetKey carries per-item identity.
        writer.AppendLine($"__builder.OpenRegion({seq});");
        writer.AppendLine($"foreach (var {node.LoopVariableName} in {node.Source.ToCode()})");
        writer.AppendLine("{");
        writer.Indent++;
        // The key is threaded into the content's root element/component so SetKey is emitted
        // immediately after that frame opens — never after OpenRegion (see BC3003).
        EmitNode(writer, node.Content, seq + 1, node.Key.ToCode());
        writer.Indent--;
        writer.AppendLine("}");
        writer.AppendLine("__builder.CloseRegion();");
        return seq + SequenceAllocator.Width(node);
    }

    private static int EmitExpansion(IndentedWriter writer, ExpansionNode node, int startSeq, string? key = null)
    {
        foreach (var local in node.Locals)
        {
            writer.AppendLine(
                $"{local.TypeName} {local.Name} = {local.Initializer.ToCode()};");
        }

        // Forward the key to the composable body's root element/component.
        return EmitNode(writer, node.Body, startSeq, key);
    }

    private static int EmitComponent(IndentedWriter writer, ComponentNode node, int seq, string? key = null)
    {
        // TypeName already carries the global:: prefix (fully qualified format).
        writer.AppendLine($"__builder.OpenComponent<{node.TypeName}>({seq});");
        if (key is not null)
            writer.AppendLine($"__builder.SetKey({key});");
        int next = seq + 1;
        foreach (var parameter in node.Parameters)
        {
            writer.AppendLine(
                $"__builder.AddComponentParameter({next}, \"{parameter.Name}\", {parameter.Value.ToCode()});");
            next++;
        }
        writer.AppendLine("__builder.CloseComponent();");
        return seq + SequenceAllocator.Width(node);
    }

    private static int EmitElement(IndentedWriter writer, ElementNode node, int seq, string? key = null)
    {
        writer.AppendLine($"__builder.OpenElement({seq}, \"{node.Tag}\");");
        if (key is not null)
            writer.AppendLine($"__builder.SetKey({key});");
        int next = seq + 1;
        next = EmitClassAttribute(writer, node.Classes, next);
        foreach (var attribute in node.Attributes)
        {
            var name = global::Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(attribute.Name, quote: true);
            writer.AppendLine($"__builder.AddAttribute({next}, {name}, {attribute.Value.ToCode()});");
            next++;
        }
        foreach (var e in node.Events)
        {
            var name = global::Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(e.Name, quote: true);
            writer.AppendLine(
                $"__builder.AddAttribute({next}, {name}, " +
                $"{EventCallbackFactory}.Create(this, {e.Handler.ToCode()}));");
            next++;
        }
        foreach (var child in node.Children)
            next = EmitNode(writer, child, next);
        writer.AppendLine("__builder.CloseElement();");
        return seq + SequenceAllocator.Width(node);
    }

    private static int EmitTextContent(IndentedWriter writer, TextContentNode node, int seq)
    {
        writer.AppendLine($"__builder.AddContent({seq}, {node.Content.ToCode()});");
        return seq + 1;
    }

    private static int EmitFragment(IndentedWriter writer, FragmentNode node, int seq, string? key = null)
    {
        // A fragment is non-keyable (BC3003 blocks it as a ForEach content root), so a threaded key would be
        // silently dropped — fail fast, mirroring EmitIf/EmitForEach.
        Debug.Assert(key is null, $"{nameof(EmitFragment)} does not support a threaded key; SetKey would be silently dropped.");
        int next = seq;
        foreach (var child in node.Children)
            next = EmitNode(writer, child, next);
        return seq + SequenceAllocator.Width(node);
    }

    private static int EmitRawMarkup(IndentedWriter writer, RawMarkupNode node, int seq, string? key = null)
    {
        Debug.Assert(key is null, $"{nameof(EmitRawMarkup)} does not support a threaded key; SetKey would be silently dropped.");
        writer.AppendLine($"__builder.AddMarkupContent({seq}, {node.Content.ToCode()});");
        return seq + 1;
    }

    private static int EmitRenderFragmentContent(
        IndentedWriter writer, RenderFragmentContentNode node, int seq, string? key = null)
    {
        // Non-keyable (BC3003 blocks it as a ForEach content root), so a threaded key would be silently
        // dropped — fail fast, mirroring EmitFragment/EmitRawMarkup.
        Debug.Assert(key is null, $"{nameof(EmitRenderFragmentContent)} does not support a threaded key; SetKey would be silently dropped.");
        writer.AppendLine($"__builder.AddContent({seq}, {node.Content.ToCode()});");
        return seq + 1;
    }

    /// <summary>
    /// Minimal indent-aware wrapper over a <see cref="StringBuilder"/>.  Line endings come from
    /// <see cref="StringBuilder.AppendLine()"/> (<see cref="Environment.NewLine"/>) so generated
    /// output stays byte-identical to the previous manual indent threading.
    /// </summary>
    /// <remarks>
    /// <see cref="System.CodeDom.Compiler.IndentedTextWriter"/> is deliberately not used: System.CodeDom
    /// is outside the netstandard2.0 shared framework and is not bundled with the packaged analyzer, so
    /// referencing it would risk a <see cref="System.IO.FileNotFoundException"/> at analyzer load time.
    /// </remarks>
    private sealed class IndentedWriter
    {
        private const string IndentUnit = "    ";

        private readonly StringBuilder _sb = new();

        /// <summary>The current indentation depth, in units of four spaces.</summary>
        public int Indent { get; set; }

        /// <summary>Appends a blank line, without leading indentation.</summary>
        public void AppendLine() => _sb.AppendLine();

        /// <summary>Appends the current indentation followed by <paramref name="text"/> and a line break.</summary>
        public void AppendLine(string text)
        {
            AppendIndent();
            _sb.AppendLine(text);
        }

        /// <summary>Appends the current indentation followed by <paramref name="text"/>, without a line break.</summary>
        public void Append(string text)
        {
            AppendIndent();
            _sb.Append(text);
        }

        public override string ToString() => _sb.ToString();

        private void AppendIndent()
        {
            for (int i = 0; i < Indent; i++)
                _sb.Append(IndentUnit);
        }
    }
}
