// <auto-generated/>
#nullable enable
using System.Collections.Immutable;

namespace BlazorCompose.Site.Content;

/// <summary>One document's navigation metadata and its build-time converted HTML.</summary>
public sealed record DocEntry(string Slug, string Title, int Order, string Html);

/// <summary>The generated documentation manifest, ordered by (Order, Slug).</summary>
public static class Docs
{
    public static readonly ImmutableArray<DocEntry> All =
    [
        new DocEntry(
            "getting-started",
            "Getting Started",
            10,
            "<p>BlazorCompose lets you write Blazor UI as plain C#. This page is itself rendered\nfrom Markdown, converted at build time and injected through <code>Html.Raw</code>.</p>\n<h2 id=\"installation\">Installation</h2>\n<p>Add the runtime and the source generator to your project, then derive your\ncomponents from <code>ComposeComponentBase</code>.</p>\n<h2 id=\"a-first-component\">A first component</h2>\n<div class=\"csharp\"><pre>\n<span class=\"keyword\">using</span> Microsoft.AspNetCore.Components;\n<span class=\"keyword\">using</span> BlazorCompose;\n<span class=\"keyword\">using</span> <span class=\"keyword\">static</span> BlazorCompose.Html;\n\n[Route(<span class=\"string\">&quot;/&quot;</span>)]\n<span class=\"keyword\">public</span> <span class=\"keyword\">partial</span> <span class=\"keyword\">class</span> Home : ComposeComponentBase\n{\n    <span class=\"keyword\">protected</span> <span class=\"keyword\">override</span> View Body =&gt;\n        Div(\n            H1(<span class=\"string\">&quot;Hello&quot;</span>),\n            Span(<span class=\"string\">&quot;Welcome to BlazorCompose.&quot;</span>));\n}\n</pre></div><h2 id=\"next-steps\">Next steps</h2>\n<ul>\n<li>Read the <a href=\"/counter\">counter sample</a> to see events, <code>If</code>, and keyed <code>ForEach</code>.</li>\n<li>Jump to <a href=\"#installation\">Installation</a> or <a href=\"#a-first-component\">A first component</a>.</li>\n</ul>\n"),
    ];

    /// <summary>Finds a document by slug. Blazor route matching is case-insensitive,
    /// so the lookup must be too.</summary>
    public static DocEntry? Find(string? slug)
    {
        if (slug is null)
        {
            return null;
        }

        foreach (var entry in All)
        {
            if (string.Equals(entry.Slug, slug, StringComparison.OrdinalIgnoreCase))
            {
                return entry;
            }
        }

        return null;
    }
}
