using BlazorCodeFirst.Site.DocGen;
using Xunit;

namespace BlazorCodeFirst.Site.DocGen.Tests;

public class CSharpDocEmitterTests
{
    private static string EmitOne(string slug, string title, int order, string html) =>
        CSharpDocEmitter.Emit([(new DocMeta(slug, title, order, DocLang.Canonical, false), html)]);

    [Fact]
    public void Emit_ProducesManifestShape()
    {
        string source = EmitOne("getting-started", "Getting Started", 10, "<p>hi</p>");

        Assert.StartsWith("// <auto-generated/>\n", source);
        Assert.Contains("namespace BlazorCodeFirst.Site.Content;", source);
        Assert.Contains(
            "public sealed record DocEntry(string Slug, string Title, int Order, string Lang, bool Stale, string Html);",
            source);
        Assert.Contains("public static readonly ImmutableArray<DocEntry> All", source);
        Assert.Contains("public static ImmutableArray<DocEntry> ForLang(string lang)", source);
        Assert.Contains("public static DocEntry? Find(string lang, string? slug)", source);
        Assert.Contains("\"getting-started\"", source);
        Assert.Contains("\"Getting Started\"", source);
        Assert.Contains("<p>hi</p>", source);
    }

    [Fact]
    public void Emit_EnablesNullableContext()
    {
        // An auto-generated file needs an explicit #nullable directive before it may use nullable
        // annotations (CS8669), and Find's signature is annotated.
        string source = EmitOne("a", "A", 1, "<p/>");

        Assert.Contains("#nullable enable", source);
        Assert.True(
            source.IndexOf("#nullable enable", StringComparison.Ordinal)
                < source.IndexOf("DocEntry? Find", StringComparison.Ordinal),
            "the directive must precede the annotated signature");
    }

    [Fact]
    public void Emit_OrdersByFrontMatterOrder()
    {
        string source = CSharpDocEmitter.Emit(
        [
            (new DocMeta("zeta", "Zeta", 30, DocLang.Canonical, false), "<p>z</p>"),
            (new DocMeta("beta", "Beta", 20, DocLang.Canonical, false), "<p>b</p>"),
            (new DocMeta("alpha", "Alpha", 10, DocLang.Canonical, false), "<p>a</p>"),
        ]);

        int alpha = source.IndexOf("\"alpha\"", StringComparison.Ordinal);
        int beta = source.IndexOf("\"beta\"", StringComparison.Ordinal);
        int zeta = source.IndexOf("\"zeta\"", StringComparison.Ordinal);

        Assert.True(alpha < beta && beta < zeta, "documents must be emitted in ascending order");
    }

    [Fact]
    public void Emit_UsesOrdinalIgnoreCaseLookup() =>
        Assert.Contains("OrdinalIgnoreCase", EmitOne("a", "A", 1, "<p/>"));

    [Fact]
    public void Emit_EscapesHtmlIntoStringLiteral()
    {
        string source = EmitOne("a", "A", 1, "<a href=\"/x\">\n</a>");

        Assert.Contains("\\\"", source);   // quotes escaped
        Assert.Contains("\\n", source);    // newlines escaped
        Assert.DoesNotContain("\r", source);
    }

    [Fact]
    public void Emit_EscapesQuotesInTitle() =>
        Assert.Contains("\\\"Quoted\\\"", EmitOne("a", "\"Quoted\"", 1, "<p/>"));

    [Fact]
    public void Emit_EscapesBackslash()
    {
        // A literal backslash must become `\\` in the generated literal, or it would combine
        // with the next character to form an unintended (or illegal) escape sequence.
        string source = EmitOne("a", "A", 1, "<p>C:\\path</p>");

        Assert.Contains("C:\\\\path", source);
    }

    [Fact]
    public void Emit_EscapesUnicodeLineTerminatorCodePoints()
    {
        // U+0085 (NEL), U+2028 (LINE SEPARATOR), and U+2029 (PARAGRAPH SEPARATOR) are all
        // classified as new-line characters by the C# lexer, so they are illegal inside a
        // non-verbatim string literal (CS1010) even though they are >= 0x20 and would
        // otherwise fall through Escape's default branch untouched. They must be emitted as
        // \uXXXX escapes. Written here as C# escapes rather than raw code points, so this test
        // file itself does not become the corruption hazard it is guarding against.
        string source = EmitOne("a", "A", 1, "<p>a\u0085b\u2028c\u2029d</p>");

        Assert.Contains("\\u0085", source, StringComparison.Ordinal);
        Assert.Contains("\\u2028", source, StringComparison.Ordinal);
        Assert.Contains("\\u2029", source, StringComparison.Ordinal);

        Assert.DoesNotContain("\u0085", source, StringComparison.Ordinal);
        Assert.DoesNotContain("\u2028", source, StringComparison.Ordinal);
        Assert.DoesNotContain("\u2029", source, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_DuplicateSlug_Throws()
    {
        var ex = Assert.Throws<InvalidOperationException>(() => CSharpDocEmitter.Emit(
        [
            (new DocMeta("dup", "One", 1, DocLang.Canonical, false), "<p>1</p>"),
            (new DocMeta("dup", "Two", 2, DocLang.Canonical, false), "<p>2</p>"),
        ]));

        Assert.Contains("dup", ex.Message);
    }

    [Fact]
    public void Emit_DuplicateOrder_Throws()
    {
        var ex = Assert.Throws<InvalidOperationException>(() => CSharpDocEmitter.Emit(
        [
            (new DocMeta("a", "A", 10, DocLang.Canonical, false), "<p>a</p>"),
            (new DocMeta("b", "B", 10, DocLang.Canonical, false), "<p>b</p>"),
        ]));

        Assert.Contains("order", ex.Message, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("10", ex.Message);
    }

    [Fact]
    public void Emit_IsDeterministic() =>
        Assert.Equal(EmitOne("a", "A", 1, "<p>x</p>"), EmitOne("a", "A", 1, "<p>x</p>"));
}
