using BlazorCodeFirst.Site.DocGen;
using Xunit;

namespace BlazorCodeFirst.Site.DocGen.Tests;

public class CSharpDocEmitterTests
{
    /// <summary>Shell text for every language the given documents are written in.</summary>
    /// <remarks>
    /// The emitter requires one per language because the site reads every reader-facing string from
    /// the manifest. What each string says is <see cref="ShellFile"/>'s business, so these are
    /// placeholders: the assertions below are about manifest shape, not about wording.
    /// </remarks>
    private static Dictionary<string, ShellStrings> ShellsFor(IEnumerable<DocMeta> metas)
    {
        var shells = new Dictionary<string, ShellStrings>(StringComparer.Ordinal);
        foreach (var meta in metas)
        {
            shells[meta.Lang] = new ShellStrings(
                meta.Lang,
                "Documentation",
                "The guide, in reading order.",
                "Every document, in reading order.",
                "Guide",
                "Language",
                "Jump to a diagnostic",
                "{shown} of {total}",
                DocGroup.All.ToDictionary(g => g, g => g + " heading", StringComparer.Ordinal),
                meta.Lang == DocLang.Canonical ? null : "This translation is behind.",
                meta.Lang == DocLang.Canonical ? null : "Read the English page");
        }

        return shells;
    }

    private static string Emit(params (DocMeta Meta, string Html)[] docs) =>
        CSharpDocEmitter.Emit(docs, ShellsFor(docs.Select(d => d.Meta)));

    private static string EmitOne(string slug, string title, int order, string html) =>
        Emit((
            new DocMeta(slug, title, "A summary.", order, DocGroup.Write, DocLang.Canonical, false, []),
            html));

    [Fact]
    public void Emit_ProducesManifestShape()
    {
        string source = EmitOne("getting-started", "Getting Started", 10, "<p>hi</p>");

        Assert.StartsWith("// <auto-generated/>\n", source);
        Assert.Contains("namespace BlazorCodeFirst.Site.Content;", source);
        Assert.Contains("    ImmutableArray<string> Anchors,\n    string Html);", source);
        Assert.Contains("public static readonly ImmutableArray<DocEntry> All", source);
        Assert.Contains("public static ImmutableArray<DocEntry> ForLang(string lang)", source);
        Assert.Contains("public static DocEntry? Find(string lang, string? slug)", source);
        // The manifest-taking overloads. DocsNav.Counterparts is written against the Find one, so
        // that a test can ask about documents this content tree does not hold (#279).
        Assert.Contains(
            "public static ImmutableArray<DocEntry> ForLang(ImmutableArray<DocEntry> docs, string lang)",
            source);
        Assert.Contains(
            "public static DocEntry? Find(ImmutableArray<DocEntry> docs, string lang, string? slug)",
            source);
        Assert.Contains("\"getting-started\"", source);
        Assert.Contains("\"Getting Started\"", source);
        Assert.Contains("<p>hi</p>", source);
    }

    [Fact]
    public void Emit_WritesTheDescriptionIntoTheEntry()
    {
        string source = Emit((
            new DocMeta(
                "intro", "Intro", "What this page answers.", 10, DocGroup.Start,
                DocLang.Canonical, false, []),
            "<p>1</p>"));

        Assert.Contains("    string Description,\n", source, StringComparison.Ordinal);
        Assert.Contains("\"What this page answers.\"", source, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_WritesTheIndexDescriptionIntoTheShellText()
    {
        string source = EmitOne("intro", "Intro", 10, "<p>1</p>");

        Assert.Contains("    string IndexDescription,\n", source, StringComparison.Ordinal);
        Assert.Contains("\"The guide, in reading order.\"", source, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_CarriesTheGroupOntoEachEntryAndIntoTheLookups()
    {
        string source = Emit(
            (new DocMeta("first", "First", "A summary.", 10, DocGroup.Start, DocLang.Canonical, false, []), "<p>1</p>"),
            (new DocMeta("last", "Last", "A summary.", 20, DocGroup.Reference, DocLang.Canonical, false, []), "<p>2</p>"));

        Assert.Contains("\"start\"", source, StringComparison.Ordinal);
        Assert.Contains("\"reference\"", source, StringComparison.Ordinal);
        Assert.Contains("public static readonly ImmutableArray<string> GroupOrder", source);
        Assert.Contains("public static ImmutableArray<DocEntry> ForGroup(string lang, string group)", source);
        Assert.Contains("public static ImmutableArray<string> GroupsFor(string lang)", source);
        Assert.Contains("public static string GroupLabel(string lang, string group)", source);
    }

    [Fact]
    public void Emit_GroupOrderIsTheNavigationOrder()
    {
        // GroupsFor walks GroupOrder, so this array is what decides where a heading appears. Emitted
        // from DocGroup.All rather than written out again, which is what keeps the two from drifting.
        string source = EmitOne("a", "A", 1, "<p/>");
        Assert.Contains(
            "[" + string.Join(", ", DocGroup.All.Select(g => $"\"{g}\"")) + "]",
            source,
            StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_WritesTheAnchorFilterCountIntoTheShellText()
    {
        string source = EmitOne("a", "A", 1, "<p/>");

        Assert.Contains("    string AnchorFilterCount,\n", source, StringComparison.Ordinal);
        Assert.Contains("\"{shown} of {total}\"", source, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_CarriesEveryGroupHeadingIntoTheShellText()
    {
        string source = EmitOne("a", "A", 1, "<p/>");

        foreach (string group in DocGroup.All)
        {
            Assert.Contains($"new GroupHeading(\"{group}\", \"{group} heading\")", source, StringComparison.Ordinal);
        }
    }

    [Fact]
    public void Emit_EnablesNullableContext()
    {
        // An auto-generated file needs an explicit #nullable directive before it may use nullable
        // annotations (CS8669), and Find's signature is annotated.
        string source = EmitOne("a", "A", 1, "<p/>");

        Assert.Contains("#nullable enable", source);
        Assert.True(
            source.IndexOf("#nullable enable", StringComparison.Ordinal)
                < source.IndexOf("DocEntry? Find", StringComparison.Ordinal),
            "the directive must precede the annotated signature");
    }

    [Fact]
    public void Emit_OrdersByFrontMatterOrder()
    {
        string source = Emit(
            (new DocMeta("zeta", "Zeta", "A summary.", 30, DocGroup.Write, DocLang.Canonical, false, []), "<p>z</p>"),
            (new DocMeta("beta", "Beta", "A summary.", 20, DocGroup.Write, DocLang.Canonical, false, []), "<p>b</p>"),
            (new DocMeta("alpha", "Alpha", "A summary.", 10, DocGroup.Write, DocLang.Canonical, false, []), "<p>a</p>"));

        int alpha = source.IndexOf("\"alpha\"", StringComparison.Ordinal);
        int beta = source.IndexOf("\"beta\"", StringComparison.Ordinal);
        int zeta = source.IndexOf("\"zeta\"", StringComparison.Ordinal);

        Assert.True(alpha < beta && beta < zeta, "documents must be emitted in ascending order");
    }

    [Fact]
    public void Emit_UsesOrdinalIgnoreCaseLookup() =>
        Assert.Contains("OrdinalIgnoreCase", EmitOne("a", "A", 1, "<p/>"));

    [Fact]
    public void Emit_EscapesHtmlIntoStringLiteral()
    {
        string source = EmitOne("a", "A", 1, "<a href=\"/x\">\n</a>");

        Assert.Contains("\\\"", source);   // quotes escaped
        Assert.Contains("\\n", source);    // newlines escaped
        Assert.DoesNotContain("\r", source);
    }

    [Fact]
    public void Emit_EscapesQuotesInTitle() =>
        Assert.Contains("\\\"Quoted\\\"", EmitOne("a", "\"Quoted\"", 1, "<p/>"));

    [Fact]
    public void Emit_EscapesBackslash()
    {
        // A literal backslash must become `\\` in the generated literal, or it would combine
        // with the next character to form an unintended (or illegal) escape sequence.
        string source = EmitOne("a", "A", 1, "<p>C:\\path</p>");

        Assert.Contains("C:\\\\path", source);
    }

    [Fact]
    public void Emit_EscapesUnicodeLineTerminatorCodePoints()
    {
        // U+0085 (NEL), U+2028 (LINE SEPARATOR), and U+2029 (PARAGRAPH SEPARATOR) are all
        // classified as new-line characters by the C# lexer, so they are illegal inside a
        // non-verbatim string literal (CS1010) even though they are >= 0x20 and would
        // otherwise fall through Escape's default branch untouched. They must be emitted as
        // \uXXXX escapes. Written here as C# escapes rather than raw code points, so this test
        // file itself does not become the corruption hazard it is guarding against.
        string source = EmitOne("a", "A", 1, "<p>a\u0085b\u2028c\u2029d</p>");

        Assert.Contains("\\u0085", source, StringComparison.Ordinal);
        Assert.Contains("\\u2028", source, StringComparison.Ordinal);
        Assert.Contains("\\u2029", source, StringComparison.Ordinal);

        Assert.DoesNotContain("\u0085", source, StringComparison.Ordinal);
        Assert.DoesNotContain("\u2028", source, StringComparison.Ordinal);
        Assert.DoesNotContain("\u2029", source, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_DuplicateSlug_Throws()
    {
        var ex = Assert.Throws<InvalidOperationException>(() => Emit(
            (new DocMeta("dup", "One", "A summary.", 1, DocGroup.Write, DocLang.Canonical, false, []), "<p>1</p>"),
            (new DocMeta("dup", "Two", "A summary.", 2, DocGroup.Write, DocLang.Canonical, false, []), "<p>2</p>")));

        Assert.Contains("dup", ex.Message);
    }

    [Fact]
    public void Emit_DuplicateOrder_Throws()
    {
        var ex = Assert.Throws<InvalidOperationException>(() => Emit(
            (new DocMeta("a", "A", "A summary.", 10, DocGroup.Write, DocLang.Canonical, false, []), "<p>a</p>"),
            (new DocMeta("b", "B", "A summary.", 10, DocGroup.Write, DocLang.Canonical, false, []), "<p>b</p>")));

        Assert.Contains("order", ex.Message, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("10", ex.Message);
    }

    [Fact]
    public void Emit_IsDeterministic() =>
        Assert.Equal(EmitOne("a", "A", 1, "<p>x</p>"), EmitOne("a", "A", 1, "<p>x</p>"));
}
