using Xunit;

namespace BlazorCodeFirst.Site.DocGen.Tests;

public class CSharpSnippetEmitterTests
{
    private static (SnippetEntry, string) Snippet(string name, string html) =>
        (new SnippetEntry(name, $"{name}.cs"), html);

    [Fact]
    public void Emit_OneSnippet_DeclaresItAsAConstOnTheSnippetsClass()
    {
        string code = CSharpSnippetEmitter.Emit([Snippet("hero", "<pre>x</pre>")]);

        Assert.Contains("public static class Snippets", code, StringComparison.Ordinal);
        Assert.Contains(
            "public const string Hero = \"<pre>x</pre>\";", code, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Always_OpensWithTheAutoGeneratedHeader()
    {
        string code = CSharpSnippetEmitter.Emit([Snippet("hero", "x")]);

        Assert.StartsWith("// <auto-generated/>\n", code, StringComparison.Ordinal);
        Assert.Contains("namespace BlazorCodeFirst.Site.Content;", code, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_HtmlWithQuotesAndNewlines_EscapesThemIntoTheLiteral()
    {
        string code = CSharpSnippetEmitter.Emit(
            [Snippet("hero", "<div class=\"csharp\">\n</div>")]);

        Assert.Contains(
            "\"<div class=\\\"csharp\\\">\\n</div>\"", code, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_ManySnippets_OrdersThemAlphabeticallyWhateverTheManifestOrder()
    {
        string code = CSharpSnippetEmitter.Emit([
            Snippet("hero", "h"),
            Snippet("counter", "c"),
            Snippet("design-time", "d")]);

        int counter = code.IndexOf("string Counter", StringComparison.Ordinal);
        int designTime = code.IndexOf("string DesignTime", StringComparison.Ordinal);
        int hero = code.IndexOf("string Hero", StringComparison.Ordinal);

        Assert.True(counter < designTime && designTime < hero);
    }

    [Fact]
    public void Emit_NoSnippets_StillEmitsACompilableClass()
    {
        string code = CSharpSnippetEmitter.Emit([]);

        Assert.Contains("public static class Snippets", code, StringComparison.Ordinal);
        Assert.EndsWith("}\n", code, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Always_EndsEveryLineWithLf()
    {
        string code = CSharpSnippetEmitter.Emit([Snippet("hero", "x")]);

        Assert.DoesNotContain('\r', code);
    }
}
